### ISSUE TITLE
ZUGFeRD2PullProvider adds null VATID

### ISSUE THREAD

**Issue by swsch** [ZUGFeRD/mustangproject#101]
ZUGFeRD2PullProvider.java, lines 382 to 384 always add a `<ram:SpecifiedTaxRegistration>` element, although the spec states on p. 64 "Kardinalität 0..1", i.e. optional.

If you don't set the buyer's VATID, you get
```
        <ram:SpecifiedTaxRegistration> 
          <ram:ID schemeID="VA">null</ram:ID> 
        </ram:SpecifiedTaxRegistration> 
```
which in turn fails verification with ZUV (I wonder how DEnull would fare, though :-).

What do the comments `//$NON-NLS-1$` in this neighbourhood mean?

If I were to touch this method `generateXML`, I probably could not refrain myself from using a StringBuilder and deleting the old (?) commented parts.

**Comment by jstaerk** [comment]
thanks, merged.
 //$NON-NLS-1$
is the (eclipse) string literals silencer, e.g. if you localize (eclipse "externalize Strings") into .properties files
 
` String abc="invoice"; //$NON-NLS-1$
`
 will not ask for a translation for "invoice" because it is considered identical in all languages.
