### ISSUE TITLE
Mustang library does not work for ZUGFeRD 2 sample invoice

### ISSUE THREAD

**Issue by uwemock** [ZUGFeRD/mustangproject#117]
I tried Mustang 1.7.2 with the sample invoice MustangGnuaccountingBeispielRE-20190610_507.pdf that has been published a couple of days ago. Mustang cannot find any metadata inside the file.

`final ZUGFeRDImporter zi = new ZUGFeRDImporter();`
`try {`
`  zi.extract("/path/to/MustangGnuaccountingBeispielRE-20190610_507.pdf");`
`} catch(final Exception e) {`
`  System.out.println("Exception");`
`  return;`
`}`
`zi.parse(); // Exception . see below`
`System.out.println(zi.containsMeta()); // false`

While `containsMetadata()` returns `false`, calling `parse()` causes the following exception:

`Exception in thread "main" java.lang.NullPointerException`
`	at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106)`
`	at org.mustangproject.ZUGFeRD.ZUGFeRDImporter.parse(ZUGFeRDImporter.java:142)`
`	at Test.main(Test.java:13)`

Accessing ZUGFeRD 1 metadata works.

**Comment by uwemock** [comment]
I found an old JAR on my build path which was still 1.2.0.

A little strange that the example code on the website works with the old version only...

**Comment by jstaerk** [comment]
The sample on https://mustangproject.org/use/#read should be the new format or is it anywhere still old? Apologies for the inconveniences, by the way, I believe someone contributed a patch and i should have added a backward compatibility - as the public interface should only require changes in  major version steps.

**Comment by uwemock** [comment]
The sample you linked to is this one:

'ZUGFeRDImporter zu=new ZUGFeRDImporter();'
'zu.extract("MustangGnuaccountingBeispielRE-20170509_505.pdf");'
'zu.parse();'
'System.out.println("Total amount: "+zu.getAmount());'

This won't work with 1.7.2. The constructor signature has changed, and you won't call `extract()` or `parse()` any more.
