### ISSUE TITLE
access to TotalPrepaidAmount in v1

### ISSUE THREAD

**Issue by swsch** [ZUGFeRD/mustangproject#118]
This seemed to be quite similar to the recent issue #115, but it turns out to have further reaching effects, as the element's parent is `ram:SpecifiedTradeSettlementMonetarySummation` in v1 and `ram:SpecifiedTradeSettlementHeaderMonetarySummation` in v2.

**Comment by jstaerk** [comment]
implementation in v2 should not be too complicated , maybe sth like three, four lines in ZUGFeRD2pullprovider:generateXML are enough

**Comment by swsch** [comment]
good estimation, see #120

**Comment by swsch** [comment]
guess what ... three lines and I managed to mess up one of them :-)
