### ISSUE TITLE
ZUGFeRD2PullProvider uses NetPrice for GrossPrice 

### ISSUE THREAD

**Issue by AlexanderBiskup** [ZUGFeRD/mustangproject#134]
The tag `<ram:GrossPriceProductTradePrice>` is populated with `currentItem.getPrice()`. This should be the gross price including VAT.

**Comment by jstaerk** [comment]
very correct, very fatal and very true, thanks a lot, it's interesting the schematron does not check this.

**Comment by heisej** [comment]
according the current German specification 2.1 dated 03/24/2020 (page 34 to 36) '<ram:GrossPriceProductTradePrice>'  is the product basic price **without** VAT but before subtracting allowances and adding charges. This is shown by many of the example files contained in the official documentation (e.g. "zugferd_2p1_EN16931_AbweichenderZahlungsempf.pdf"). 
Therefore it had been correct before as mustang does not deal with allowances and charges yet.
