### ISSUE TITLE
ZUGFeRD2PullProvider doesn't support TradeAllowanceCharges

### ISSUE THREAD

**Issue by AlexanderBiskup** [ZUGFeRD/mustangproject#135]
Allowance charges are supported in the interface model of the item but have no effect on the generated xml. The corresponding section is commented out. 

```java
// + " <AppliedTradeAllowanceCharge>\n"
	// + " <ChargeIndicator>false</ChargeIndicator>\n"
	// + " <ActualAmount currencyID=\"EUR\">0.6667</ActualAmount>\n"
	// + " <Reason>Rabatt</Reason>\n"
// + " </AppliedTradeAllowanceCharge>\n"
```

**Comment by jstaerk** [comment]
I might start implementing it for ZF2 but I need your help. First: does it work with ZF1? could you provide a test?

**Comment by jstaerk** [comment]
Charges and allowances are now implemented in Mustang2 Alpha
