### ISSUE TITLE
ZUGFeRD2: Currency is not changeable, everytime EUR

### ISSUE THREAD

**Issue by JanAKQ** [ZUGFeRD/mustangproject#150]
When creating a ZUGFeRD1 invoice, currency is changeable by overwriting this function
`	public String getCurrency() {
			return "USD";
	}
`
But when you Change the same Code to ZUGFeRD2 
`ze.setFacturX();`
the currency in the XML is EUR. Without setFacturX (ZUGFeRD1 it does work), but I Need ZUGFeRD2.

**Comment by jstaerk** [comment]
That should actually be quite easy, in src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java lines 464 and 535 replacing EUR with trans.getCurrency() could already work. One could add the unit test in ZF2EdgeTest and validate /target/testout-ZF2newEdge.pdf. Do you want to check (mvn clean package) and send me a pull request?

**Comment by JanAKQ** [comment]
Thank you, I saw this lines and I think that's the solutions. But I'm sorry, I can't alter the code, because I'm not neither familiar in developing with jave nore eclipse IDE. I'm happy that I can use your Java example and I was able to modify it for my needs. Your description for using it in eclipse is very good! Now I tried to modify your library code in eclipse, but I wasn't able to do it. I don't know how to load the project, and I don't know creating a jar. I am a C# developer and I use Visual Studio.

**Comment by JanAKQ** [comment]
mustangproject-master imported. 116 Errors...

**Comment by JanAKQ** [comment]
Now no error (31 Warnings).

**Comment by JanAKQ** [comment]
But how to build with eclipse?

**Comment by JanAKQ** [comment]
Thank you! Now after reading some Java tutorials it worked. Now I try to send a pull request...

**Comment by JanAKQ** [comment]
PullRequest #151 created.
