### ISSUE TITLE
utf-8 encoding failure while updating xml files from zugferd 1 to 2

### ISSUE THREAD

**Issue by AKnoppGSE** [ZUGFeRD/mustangproject#152]
Option -u (updating zugferd version 1 to 2) in mustang-1.7.5.jar:
Updating xml zugferd version 1 files to version 2 produces wrong utf-8 code for German umlauts and special characters like ß, ° etc.
See files attached (produced with Win 10).

[zf1.zip](https://github.com/ZUGFeRD/mustangproject/files/4122676/zf1.zip)

**Comment by jstaerk** [comment]
Hi,
can you please check if it works if you use `java -Dfile.encoding=UTF-8 -jar mustang.jar -u` helps? Some OSes don't seem to expect jar files to contain UTF-8, for whatever reason.

thanks and kind regards
Jochen

PS: The feature is highly experimental and will be removed if there are no contributions to improve it.

**Comment by jstaerk** [comment]
closing due to lack of feedback
