### ISSUE TITLE
ZUGFeRD2PullProvider needs getDueDate() although getPaymentTermDescription() is defined

### ISSUE THREAD

**Issue by heisej** [ZUGFeRD/mustangproject#155]
When using getPaymentTermDescription() to specify the payment terms one still has to define getDueDate() as well. 
This is caused by following lines where `paymentTermsDescription` is always 'null' for the first if-block. Therefore the fallback string is constructed in any case before even testing for a supplied description.

Exchanging the two if-Blocks would correct both issues and be the correct way to implement this.

https://github.com/ZUGFeRD/mustangproject/blob/496c6bdfe166132db7f2219b26703c042b7f319c/libraryBasic/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java#L255-L261

**Comment by jstaerk** [comment]
that would be great, can you issue an according pull request?
