### ISSUE TITLE
Follow up to issue #134: Using price incl. VAT as product gross price is incorrect

### ISSUE THREAD

**Issue by heisej** [ZUGFeRD/mustangproject#159]
Issue #134 stated that the product gross price should be the net price plus VAT.

According the current German specification 2.1 dated 03/24/2020 (page 34 to 36) `<ram:GrossPriceProductTradePrice>` is the product basic price without VAT but before subtracting allowances and adding charges. This is shown by many of the example files contained in the official documentation (e.g. "zugferd_2p1_EN16931_AbweichenderZahlungsempf.pdf").
Therefore just using the product net price as product gross price had been correct before as mustang does not deal with allowances and charges yet.

**Comment by jstaerk** [comment]
The TA of the spec says "Bruttopreis" which does not contain allowances or charges but that does not cover taxes, i.e. a Bruttopreis is a  "Preis, der eine eventuell zu entrichtende Mehrwertsteuer o. Ä. enthält" (Duden). I'll raise it and we'll check upstream, I could imagine an error in the samples because intra-line calculations are not validated at all (e.g. not via the CEN schematron).

**Comment by heisej** [comment]
Problem is we are talking business speech here and not common people, and thus Duden, speech. In trading business it's common practice to talk of "Bruttopreis" if you mean the price before subtracting allowances but without VAT. This is probably cause by the fact that for trading companies (though not end users) VAT is not that interesting as they get it back from the tax office for goods they just buy and resell and don't use themselves.

Beside that, as mentioned above, on page 34 the German TA for the element `GrossPriceProductTradePrice` explicitly states:
>`ChargeAmount`                                                                            Bruttopreis des Artikels
> Datentyp: udt:AmountType
> Beschreibung: Der Einheitspreis **ohne** Umsatzsteuer vor Abzug des Nachlass auf den 
> Artikelpreis.

and even EN 16931-1 says the same for the relevant business element BT-148.

**Comment by jstaerk** [comment]
you are right, EN16931-1 also says "der Einheitspreis ohne Umsatzsteuer vor Abzug des Nachlass auf den Artikelpreiss",
I pushed a change to mustang 2, I will have to correct few more tests and this may be worth a 1.7.8.
