### ISSUE TITLE
Is it possible to convert PDF/A-1b to PDF/A-1a 

### ISSUE THREAD

**Issue by DivyaAppidi** [ZUGFeRD/mustangproject#168]
Hi Team
We are using print manager tool to generate our EInvoice pDF which supports only PDF/A-1b output.
Whereas mustang.jar expects the source PDF to be in PDF-A/1a format. Is it possible to have an option in mustang.jar to convert from 1b to 1a automatically and then combine with the xml to form the Zugferd PDF?

**Comment by jstaerk** [comment]
As mentioned in my answer on #167 PDF-A/1a should not be neccessary but if you want to convert anything PDFish to valid PDF-A I recommend you to have a look at my ghostscript-related comment on https://github.com/ZUGFeRD/mustangproject/issues/164#issuecomment-640046774

**Comment by jstaerk** [comment]
can't see any action to take from my side
