### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by Cakmakli-a** [ZUGFeRD/mustangproject#170]
When can we expect the next release of the library? Is there a schedule for the next release?

**Comment by jstaerk** [comment]
There is the alpha https://www.mustangproject.org/files/Mustang-CLI-2.0.0-alpha1.jar and the https://github.com/ZUGFeRD/mustangproject/blob/master/Release_Notes.md . 24 september would be a great occasion to publish another prerelease. But we need as much help as we can possibly get.

 There is a paragraph for the open todos in  https://github.com/ZUGFeRD/mustangproject/blob/master/History.md , maybe you would like to contribute?
