### ISSUE TITLE
Ist das "Profil" richtig?

### ISSUE THREAD

**Issue by Cakmakli-a** [ZUGFeRD/mustangproject#172]
https://github.com/ZUGFeRD/mustangproject/blob/c5c457ed4b8471b486ab9e0d4af26a54678996b8/library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java#L158

Wird hier nicht folgendes erwartet!? 

`urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.0`

Da die Regel lautet wie folgt:

```
<param name="BR-DE-21"
    value="ram:GuidelineSpecifiedDocumentContextParameter/ram:ID = 
'urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.0'" />
```

Siehe unter [Kosit Schematron](https://github.com/itplr-kosit/xrechnung-schematron/blob/master/validation/schematron/cii/CII/XRechnung-CII-model.sch)

**Comment by heisej** [comment]
Der zurückgelieferte String müßte eigentlich vom verwendeten Profil abhängen. Da die Bibliothek als Standard das ehemalige COMFORT-Profil (jetzt EN 16931) erzeugt ist der String korrekt. Das steht so auch in der aktuellen ZUGFeRD Spezifikation.

Der andere String, der in auskommentierter Form im Quelltext schon vorhanden ist, müßte beim Profil XRECHNUNG verwendet werden, um die Kompatibilität zum XRECHNUNG-Format herzustellen (neben einigen anderen Werten).

**Comment by Cakmakli-a** [comment]
Das sehe ich genauso. Stattdessen wird hier hardcoded:

```
	@Override
	public String getProfile() {
//		return "urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_1.2";
		return "urn:cen.eu:en16931:2017";
	}
```

Warum dann die Möglichkeit bieten wie:

```
	@Override
	public void setProfile(ZUGFeRDConformanceLevel level) {
		this.level = level;
	}
```

Wenn eh nicht davon Gebrauch gemacht wird:

`<ram:ID>" + getProfile() + "</ram:ID>\n"`

**Comment by heisej** [comment]
Der Entwicklungsstand, über den wir hier sprechen ist ja "Work in progress" und keine Release-Version. 
Es wird ja keiner daran gehindert den Code entsprechend zu ergänzen und hier einen Pull-Request zu machen. Jochen freut sich bestimmt, wenn noch andere mitprogrammieren, da er das Projekt ja mehr oder weniger in seiner Freizeit betreut.

Ich selbst habe für unseren Firmenbedarf im Bereich ZUGFeRD-Erzeugung letztens auch einige Sachen ergänzt und Fehler beseitigt, die Jochen ohne Diskussion in den Hauptzweig aufgenommen hat.

**Comment by jstaerk** [comment]
ZUV bzw. seit neuestem die Validierungsbibliothek von Mustang 2 (alpha) meldet tatsächlich nur notices wenn ein EN16931-Format vorliegt. Wird das in ZF2.1.1 spezifizierte "Referenzprofil" XRechnung verwendet schaltet sich die Fehlerstufe von Notice auf Error.

Folgendes wäre noch schön
- nicht nur XR 1.2.2 sondern auch XR 2.0 (ab 01.01. verpflichtend) validieren können. Dafür gibt es nur meines Wissens seitens Kosit noch keine Schematrondateien.
- notices per Kommandozeile abschalten können (manchmal nervt's)
- logs per Kommandozeile  abschalten können (mit log4j möglich mit slf4j praktisch nicht)
- ich hatte gestern mal reingeschaut weil derzeit noch dokumentiert ist eine deprecated-Funktion zu benutzen um XRechnung direkt zu bekommen. Die nicht-deprecated-Funktion geht über Factories aber es gibt noch keine Factory ohne PDF-Ausgabe
- in dem Zusammenhang könnte man auch prüfen ob man die Angabe eines IProfileProvider irgendwo unterbringen kann der dann die korrekte GuidelineID für die XR liefern könnte

**Comment by Cakmakli-a** [comment]
> Wird das in ZF2.1.1 spezifizierte "Referenzprofil" XRechnung verwendet

Die XRechnung (XML), die Mustang2 produziert, ist mit welcher Version von XRechnung "konform"? Für mich leider noch unklar.

**Comment by jstaerk** [comment]
Dasselbe XML ist - abgesehen von der angegebenen Versionsnummer - für XR 1.2.2 und XR 2.0 gültig, da 1.2.2 zum 31.12. abgeschafft wird (https://www.xoev.de/xrechnung-16828) habe ich mal 2.0 eingetragen . Die Profile der XRechnung sind zwar eigentlich "Standard" und "Extension" aber ich hab jetzt mal die Guideline-ID des "Referenzprofils" Xrechnung gekapert. Ich habe den Test (https://github.com/ZUGFeRD/mustangproject/blob/master/library/src/test/java/org/mustangproject/ZUGFeRD/XRTest.java) erweitert, unter anderem um einen Kontakt und eine Leitweg-ID ergänzt und vor allem wird es jetzt automatisch auch validiert (https://github.com/ZUGFeRD/mustangproject/blob/master/validator/src/test/java/org/mustangproject/validator/LibraryTest.java), aber der Kern dieses Issues war berechtigt, die Guideline-ID fehlte.
