### ISSUE TITLE
SpecifiedTradeAllowanceCharge with same taxes are enumerated instead of summed

### ISSUE THREAD

**Issue by weclapp-dev** [ZUGFeRD/mustangproject#191]
If there are shippingCosts and document specific discount then the result is invalidDoc.pdf (pdf errors can be ignored). The right document should look like validDoc.pdf.
[validDoc.pdf](https://github.com/ZUGFeRD/mustangproject/files/5547043/validDoc.pdf)
[invalidDoc.pdf](https://github.com/ZUGFeRD/mustangproject/files/5547044/invalidDoc.pdf)

**Comment by jstaerk** [comment]
since PR 192 has been merged this is now solved?

**Comment by weclapp-dev** [comment]
Yes, it is solved. Thank you.
