### ISSUE TITLE
Missing quotation marks lead to XML generation error.

### ISSUE THREAD

**Issue by tilomlr** [ZUGFeRD/mustangproject#197]
I tried to add some attachments but didn't working. The problem is a missing quotation mark.

https://github.com/ZUGFeRD/mustangproject/blob/82dd4cf131264a348a46a8e6bee8ecb3e053ea6c/library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java#L445

**Comment by jstaerk** [comment]
you are right, thanks, it would be great if we had tests for that
