### ISSUE TITLE
Missing </ram:AttachmentBinaryObject> xml-tag

### ISSUE THREAD

**Issue by GitThLo** [ZUGFeRD/mustangproject#200]
https://github.com/ZUGFeRD/mustangproject/blob/82dd4cf131264a348a46a8e6bee8ecb3e053ea6c/library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java#L444

The xml-tag "<ram:AttachmentBinaryObject ..." is not closed and throws an error.

**Comment by jstaerk** [comment]
dupes #197 and is already fixed
