### ISSUE TITLE
The closing Tag is still missing

### ISSUE THREAD

**Issue by tilomlr** [ZUGFeRD/mustangproject#201]
The closing tag is still missing.

https://github.com/ZUGFeRD/mustangproject/blob/82dd4cf131264a348a46a8e6bee8ecb3e053ea6c/library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java#L445

**Comment by jstaerk** [comment]
please feel free to pull the most recent version and build yourself or wait for the next version.

**Comment by tilomlr** [comment]
This bug is not a duplicate, it's a different one. The closing Tag </ram:AttachmentBinaryObject> is not present in the code.

**Comment by jstaerk** [comment]
you were right, thanks, added a method in the invoice class and unit tests so that this can not happen any more. Will come in the next version (2.0.3?)

**Comment by tilomlr** [comment]
@jstaerk thank you very much
