### ISSUE TITLE
How to add payment instructions?

### ISSUE THREAD

**Issue by murygin** [ZUGFeRD/mustangproject#203]
I create an invoice with the Mustang library. When I check the generated invoice with the validator I get the message:
```
<notice type="27" location="/*:CrossIndustryInvoice[namespace-uri()='urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100'][1]" criterion="rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTrade
Settlement/ram:SpecifiedTradeSettlementPaymentMeans">[BR-DE-1] Eine Rechnung (INVOICE) muss Angaben zu "PAYMENT INSTRUCTIONS" (BG-16) enthalten.</notice>
```
How can I add payment instructions?

**Comment by jstaerk** [comment]
Hi,
Assuming you are using the class and not the interface that would be adding bank details to the sender, i.e. `.addBankDetails(new BankDetails("IBANID","BIC"))) ` as in https://www.mustangproject.org/invoice-class/#xrechnung
