### ISSUE TITLE
Rounding error with charges and allowances

### ISSUE THREAD

**Issue by jstaerk** [ZUGFeRD/mustangproject#212]
[factur-x.orig.txt](https://github.com/ZUGFeRD/mustangproject/files/5735691/factur-x.orig.txt)
LineTotalAmount ChargeTotalAmount AllowanceTotalAmount are correct, but TaxBasisTotalAmount (then GrandTotalAmount and DuePayableAmount) is one cent off. Validator correctly fails with ` <error type="4" location="/*[local-name()='CrossIndustryInvoice']/*[local-name()='SupplyChainTradeTransaction']/*[local-name()='ApplicableHeaderTradeSettlement']/*[local-name()='SpecifiedTradeSettlementHeaderMonetarySummation']" criterion="(ram:TaxBasisTotalAmount = (round(ram:LineTotalAmount*100 - ram:AllowanceTotalAmount*100 + ram:ChargeTotalAmount*100) div 100)) or ((ram:TaxBasisTotalAmount = (round(ram:LineTotalAmount*100 - ram:AllowanceTotalAmount*100) div 100)) and not (ram:ChargeTotalAmount)) or ((ram:TaxBasisTotalAmount = (round(ram:LineTotalAmount*100 + ram:ChargeTotalAmount*100) div 100)) and not (ram:AllowanceTotalAmount)) or ((ram:TaxBasisTotalAmount = (round(ram:LineTotalAmount * 100) div 100)) and not (ram:ChargeTotalAmount) and not (ram:AllowanceTotalAmount))">Invoice total amount without VAT (BT-109) = S Invoice line net amount (BT-131) - Sum of allowances on document level (BT-107) + Sum of charges on document level (BT-108).</error>` . Probably LineTotalAmount is not rounded to two digits before adding charges and substracting allowances.

**Comment by omocinteractive** [comment]
Perfect. I hope some problems with rounding are now corrected in my project. I will give you a feedback it its not.
