### ISSUE TITLE
Contact of recipient TradeParty is ignored in XRechnung

### ISSUE THREAD

**Issue by seeeeew** [ZUGFeRD/mustangproject#216]
I want to set the field BT-58 "Buyer contact email address" in an XRechnung invoice because a customer requested it, but I can't get it to work. I tried setting the Contact of the recipient TradeParty accordingly, but that seems to be ignored entirely.

As far as I can tell, it should end up in `ram:BuyerTradeParty/ram:DefinedTradeContact/ram:EmailURIUniversalCommunication/ram:URIID` in the resulting XRechnung XML, but judging by the Mustang source code the Contact of the recipient TradeParty is only used in the EXTENDED ZUGFeRD profile, while being completely ignored in the XRECHNUNG profile.

Am I doing it wrong or is this not supported?

**Comment by jstaerk** [comment]
AFAIL the attribute is even required in all XRechnung files and it is supported, see e.g. the sample in https://www.mustangproject.org/invoice-class/#xrechnung which generates the according https://www.mustangproject.org/files/xrechnung.xml

**Comment by seeeeew** [comment]
Thanks for the fast response! In the links you provided only the seller/sender contact is set, but not the _buyer/recipient_ contact. I've already tried to set the contact for the buyer/recipient in the same way, but it didn't appear in the generated XML.

**Comment by seeeeew** [comment]
I copied the following piece of code verbatim from the *Corrected invoice* example on the page you linked into my code:
```java
.setRecipient(new TradeParty("Franz Müller", "teststr.12", "55232", "Entenhausen", "DE") .setContact(new Contact("nameRep", "phoneRep", "emailRep@test.com")))
```
The generated XML contains this:
```xml
<ram:BuyerTradeParty> 
  <ram:Name>Franz Müller</ram:Name>  
  <ram:PostalTradeAddress> 
    <ram:PostcodeCode>55232</ram:PostcodeCode>  
    <ram:LineOne>teststr.12</ram:LineOne>  
    <ram:CityName>Entenhausen</ram:CityName>  
    <ram:CountryID>DE</ram:CountryID> 
  </ram:PostalTradeAddress> 
</ram:BuyerTradeParty> 
```
Only the basic data of the _buyer/recipient_ TradeParty ended up in the XML, but the Contact didn't.

**Comment by seeeeew** [comment]
@jstaerk I hope it's okay to bring this up again, I wasn't sure about the proper etiquette.

I have reviewed the examples on the page you linked, as well as the [relevant Mustang code](https://github.com/ZUGFeRD/mustangproject/blob/597075e0dc7ace1b25a2ca47561cd49973fe2b59/library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java#L132-L156). Setting a Contact for the _buyer/recipient_ TradeParty is currently only supported for the ZUGFeRD Extended profile, not for the XRechnung profile. Is this by design? The format specification for XRechnung seems to indicate this should work the same for both TradePartys.
