### ISSUE TITLE
Uber-Jar - Warum?

### ISSUE THREAD

**Issue by Cakmakli-a** [ZUGFeRD/mustangproject#227]
Warum wurde entschieden aus der "Library" eine Uber-Jar zu machen?
Ich sehe darin nur Probleme. Z.B. Versionskonflikte.
Ist ein durchdachtest Dependency-Management nicht mehr möglich!?

**Comment by jstaerk** [comment]
Der Grund für die Änderung des primären Deployment war, war erstens, dass niemand dagegen gestimmt hat (https://groups.google.com/g/zugferd/c/Riml-eJmH70), es zweitens für den Menschen der den ursprünglichen PR eingebracht hatte OK war (https://github.com/ZUGFeRD/mustangproject/pull/219) und ich es drittens ansonsten nicht hingekriegt habe die CII zu UBL-Umwandlung in der JAR der CLI zum laufen zu bringen. Außerdem ist bin ich mir viertens nicht sicher, ob das ungeshadete JAR nicht auch auf maven central wandert und per Classifier zur Verfügung steht.
Falls es dafür eine bessere Möglichkeit gibt: immer raus damit, sprich gerne PR.

**Comment by Andreas-LBC** [comment]
Hallo Jochen,

ich bin ein Kollege von Adem und wir versuchen, ein möglichst dediziertes Setup in einer RedHat EAP Serveranwendung umzusetzen. 
Ich denke, es wäre schon gut, ein entsprechendes Artifact bereitzustellen, idealerweise als BOM. So könnten wir uns ein Mustang Single Deployment und den dann bekannten Abhängigkeiten mit entsprechender Versionen selbst zusammen konfigurieren; zum Teil sind gängige Module / Dependencies bereits im JBoss Ökosystem vorhanden. 
Ich denke auch, dass mit diesen Informationen  andere Entwickler und Architekten mehr anfangen könnten. 
Wir bitten Dich im ersten Schritt um die Unterstützung, alle Artifacts in Version zu nennen und eine SingleDistribution der Mustang Jar bereitzustellen. Idealerweise auch in Java 8 kompiliert. 

Beste Grüße,
Andreas

**Comment by jstaerk** [comment]
Einen entsprechenden PR würde ich sehr begrüßen, wie gesagt seid bitte nur so nett und testet in der CLI kurz die CII to UBL-Konvertierung durch. Vielen Dank schon vorweg!

**Comment by Andreas-LBC** [comment]
Wir besprechen uns. Danke fürs Feedback.

**Comment by mfernau** [comment]
Hallo zusammen,

ich möchte mich an dieser Stelle auch kurz melden, da es durch Mustang in unserer Anwendung nun zu Mischungen der SLF4J und damit zu Fehlern kommt. Das liegt daran, weil in der Mustang-Library teile von SLF4J integriert sind und durch andere Libraries bei uns (welche ebenfalls SLF4J benötigen) verwendet werden - aber eben in der falschen Version. Das bringt uns leider vor gravierende Probleme. Wenn es also keine einfach Lib (ohne Abhängigkeiten) von Mustang gib und es uns somit nicht möglich ist die transitiven Abhängigkeiten durch unser Build-Tool auflösen zu lassen, muss ich Mustang aus unserer Anwendung ausgliedern und als externe Anwendung nur bei Bedarf starten. Das macht leider alles wesentlich komplizierter als nötig.
Gibt es hier Bestrebungen die Uber-Jar wieder in eine "einfache" lib umzuwandeln?

Schöne Grüße
Martin

**Comment by jstaerk** [comment]
Ich kann nicht genug betonen, wie sehr ich mich über einen pull request freuen würde, der das Über-JAR vermeidet und mit dem trotzdem in der CLI die CII-to-UBL-Umwandlung funktioniert.

**Comment by jstaerk** [comment]
Thanks a lot for the PR, will come in the next version

**Comment by florianklumb** [comment]
Hi Jochen,

Coming from your reply in #262 we looked into the source and JAR and it seems the PR was - at least in parts - overwritten by recent commits so shading was deactivated again. What was the reasoning behind this?

Thanks

Florian

**Comment by florianklumb** [comment]
We linked our project to a self-compiled JAR of #257 and it works. So we would really like a shaded version of Mustang!
