### ISSUE TITLE
How to fill project reference?

### ISSUE THREAD

**Issue by smejkal** [ZUGFeRD/mustangproject#229]
How can I fill the project reference? Or is the project reference not part of the implementation?

**Comment by jstaerk** [comment]
That depends on if you (a) or your customer (b) assigned the project, how formal the project is (do you have a contract (c), an order (d) or an procurement (e)) and if you want to refer to it on item (f) or document level (g):

 I suggest the technical appendix of the ZUGFeRD specification.

What do you need?

(a) could be SupplyChainTradeTransaction/IncludedSupplyChainTradeLineItem/SpecifiedTradeProduct/SellerAssignedID
(b) buyerassignedID
(c) contractReferencedDocument
(d) buyerOrderReferencedDocument
(e) SpecifiedProcuringProject (this one is indeed not yet implemented in Mustang)
(f) / (g) I believe there something like SellerAssignedID also on document level

**Comment by smejkal** [comment]
Thanks, I found SpecifiedProcuringProject in the specification, that would be appropriate.

I implemented the type:

```
<ram:SpecifiedProcuringProject> 
   <ram:ID>10212</ram:ID> 
   <ram:Name>World peace</ram:Name> 
</ram:SpecifiedProcuringProject> 

```
Ultramarin eRechung Viewer views only the ID, not the name.

**Comment by jstaerk** [comment]
If you want to integrate that in Mustang the steps would be 

1. have a unit test in **validator**, in validator/src/test/java/org/mustangproject/validator/LibraryTest.java, which creates a file with a procuring project, confirms that the file is valid, and checks that the info is there, e.g. the procuring project ID is mentioned in the XML: the functionality is required in the library but the unit test in the validator allows to also validate that the generated XML was valid.
2. in **library** create something like a IProcuringProject interface with getName and getID, and create a class implementing that interface (e.g. ProcuringProject)
3. in library/src/main/java/org/mustangproject/ZUGFeRD/IExportableTransaction.java, add something like `default IProcuringProject getProcuringProject() { return null; }`
4. in library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java check if trans.getProcuringProject()!=null, in which case you add the according lines with XMLEncoded values (roughly e.g. XMLTools.encodeXML(trans.getProcuringProject().getName())) to the XML (at the right place)
5. in library/src/main/java/org/mustangproject/Invoice.java add a property for the ProcuringProject **class**, add a setter, and add a compatible `IProcuringProject getProcuringProject()` getter.
6. Now you should be able to set a ProcuringProject in the invoice class.
