### ISSUE TITLE
have unit tests for nDigitFormat

### ISSUE THREAD

**Issue by jstaerk** [ZUGFeRD/mustangproject#23]
test cases are already documented in the comments of the function :-)

**Comment by swsch** [comment]
I'm confused about nDigitFormat in class ZUGFeRDTransactionModelConverter, as it takes a BigDecimal argument, returns a BigDecimal argument, but still takes a round-trip through String-land.

Shouldn't 
```
	private BigDecimal nDigitFormat(BigDecimal value, int scale) {
		return value.setScale(scale, BigDecimal.ROUND_UP);
	}
```
be enough in this situation?

**Comment by swsch** [comment]
The nDigitFormat method in class ZUGFeRD2PullProvider seems to do what [BigDecimal.toPlainString](https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html#toPlainString--) does.

That would make this method a simple wrapper:
```
	private String nDigitFormat(BigDecimal value, int scale) {
		return value.setScale(scale, BigDecimal.ROUND_UP).toPlainString();
	}
```

`mvn test` succeeds with these implementation, so I'll prepare a PR for review.

**Comment by jstaerk** [comment]
> 
> ```
> 	private BigDecimal nDigitFormat(BigDecimal value, int scale) {
> 		return value.setScale(scale, BigDecimal.ROUND_UP);
> 	}
> ```
> 
> be enough in this situation?

should probably be ROUND_HALF_UP but yes, sorry, it's confusing, I removed it. Without unit tests in the first place which were only for the string returning ndigitformat (crossing fingers)
