### ISSUE TITLE
Wrong year in History.md

### ISSUE THREAD

**Issue by asdf00000** [ZUGFeRD/mustangproject#231]
Release dates of version 2.1.0 and 2.1.1. should be year 2021, not 2020.

**Comment by jstaerk** [comment]
where?

**Comment by asdf00000** [comment]
As I wrote, in History.md under versions 2.1.0 and 2.1.1.
https://github.com/ZUGFeRD/mustangproject/blob/master/History.md

**Comment by jstaerk** [comment]
corrected, thanks
