### ISSUE TITLE
falscher Text in Exception

### ISSUE THREAD

**Issue by asdf00000** [ZUGFeRD/mustangproject#237]
Im CLI-Modul, Datei `Main` in Zeile 800 muss es heißen `File  %s already exists` statt `File %s does not exists`. Momentan besagt die Meldung das Gegenteil von dem, was sie eigentlich sollte.

https://github.com/ZUGFeRD/mustangproject/blob/master/Mustang-CLI/src/main/java/org/mustangproject/commandline/Main.java

**Comment by jstaerk** [comment]
Richtig, danke für den Hinweis
