### ISSUE TITLE
Validierungsproblem mit Skonto

### ISSUE THREAD

**Issue by asdf00000** [ZUGFeRD/mustangproject#238]
Ich habe eine XRechnung mit Hilfe von `IExportableTransaction `erstellt. Validierung soweit ok.
Wenn ich nun in den `IZUGFeRDPaymentTerms` das Interface `IZUGFeRDPaymentDiscountTerms` verwende, um ein Skonto anzugeben, treten beim Validieren Fehler auf:

aus der XRechnung:
...
`
<ram:SpecifiedTradePaymentTerms>
        <ram:Description>Skonto</ram:Description>
        <ram:ApplicableTradePaymentDiscountTerms>
          <ram:BasisAmount currencyID="EUR">124.69</ram:BasisAmount>
          <ram:CalculationPercent>3</ram:CalculationPercent>
          <ram:BasisDateTime>
            <udt:DateTimeString format="102">20210319</udt:DateTimeString>
          </ram:BasisDateTime>
          <ram:BasisPeriodMeasure unitCode="DAY">7</ram:BasisPeriodMeasure>
        </ram:ApplicableTradePaymentDiscountTerms>
      </ram:SpecifiedTradePaymentTerms>  
`
...

aus der Validierung:

...
`<error type="18">schema validation fails:org.xml.sax.SAXParseException; lineNumber: 171; columnNumber: 30; cvc-complex-type.2.4.a: Ungültiger Content wurde beginnend mit Element '{"urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100":BasisDateTime}' gefunden. '{"urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100":ActualDiscountAmount}' wird erwartet.</error>`
...

**Comment by jstaerk** [comment]
ich bräuchte bitte mal die komplette xrechnung. Und am besten den Quelltext.

**Comment by asdf00000** [comment]
Habe mal ein Beispiel auf Basis der Klasse MustangWriter erstellt.
XRechnung:
https://github.com/asdf00000/test/blob/main/XRechnung.xml
Code:
https://github.com/asdf00000/test/blob/main/MustangSimpleTest.java

**Comment by jstaerk** [comment]
Danke.
Wäre es fx extended o.ä. müsste BasisAmount und CalculationPercent offensichtlich hinter BasisPeriodMeasure. Das ist schonmal ein Fehler und ich hoffe ich hab nochmal irgendwann kurz Zeit um das zu korrigieren. Und dafür lasse ich den Bug mal offen.

Spannenderweise kriegen wir Ihre Rechnung nämlich trotzdem valide wenn Sie sie IZUGFeRDPaymentTerms ändern in 
```
			@Override
			public String getDescription() {
				return "#SKONTO#TAGE=7#PROZENT=3.00#BASISBETRAG=571.04#";
			}
			@Override
			public Date getDueDate() {
				return null;
			}
			@Override
			public IZUGFeRDPaymentDiscountTerms getDiscountTerms() {
				return null;
			};

```
Hintergrund: Skonto für B2G-Rechnungen sind relativ typisch Deutsch und das entsprechende XML-Feld (ApplicableTradePaymentDiscountTerms) hat es deshalb nicht einmal optional in den EN16931-Umfang geschafft. Die XRechnung kodiert die Skontoinformationen deshalb nicht in XML sondern notgedrungendermaßen in einem proprietären Format in die Description (s. Spezifikation der XRechnung 2.0, Kap 13.2 Umgang mit Skonto insbesondere auch S. 36).

**Comment by asdf00000** [comment]
Vielen Dank, das hilft weiter.

**Comment by asdf00000** [comment]
Hinweis:
Die Skonto-Zeile muss wohl mit einem Zeilenumbruch enden.
Dem Mustang-Validator ist es egal, aber der KoSIT-Validator bemängelt das sonst als Fehler:

`Am Ende einer vollständigen Skonto oder Verzugsangabe muss ein XML-konformer Zeilenumbruch folgen.`
...
`Bewertung: Es wird empfohlen das Dokument zurückzuweisen.`

Das kann also dazu führen, dass die Rechnung vom Empfänger abgelehnt wird, wenn dieser mit dem KoSIT-Validator validiert.

**Comment by jstaerk** [comment]
closed in current master
