### ISSUE TITLE
Fehlermeldung (Rechenfehler) bei Nutzung Rounding amount (BT-114)

### ISSUE THREAD

**Issue by BoHamburg** [ZUGFeRD/mustangproject#239]
Um den durch Roundungsfehler unterschiedlichen Brutto-Betrag einer Rechnung auszugleichen, (Bruttopreise als Ausgangspreise werden in Nettopreis umgerechnet) und dann die

- Berechnung und Addierung der Mwst. pro Positionszeile erfolgt

oder die

- Addierung der Nettopreise pro Positionszeile erfolgt und abschließend die Mwst. Berechnung

bietet sich die Angabe von "RoundingAmount" (BT-114) an.

Beispiel, Bruttobetrag des Artikels, 19,95:

19,95 / 1,19 = Nettopreis 16,76(47) = 16,76
16,76 * 1,19 = Bruttopreis 19,94(44) = 19,94

Gebe ich dann den 1 Cent different als "Rounding amount" an, kann ich den Betrag "Amount due for payment" auf 19,95 setzen.

Leider scheint Mustang intern anders zu rechnen / zu runden (*100 ... / 100), als es in der Fehlermeldung angibt, bzw. in der ZUGFeRD Doku steht...

**Amount due for payment (BT-115) = Invoice total amount with VAT (BT-112) -Paid amount (BT-113) +Rounding amount (BT-114).**

Ändernt man den Preis um Faktor 100, scheint das beim Runden dann kein Problem zu sein... (sieh Datei ..._x100.xml

Als Zip-File, zwei Test-Rechnungen und die Fehlermeldungen.
[Mustang.zip](https://github.com/ZUGFeRD/mustangproject/files/6310685/Mustang.zip)

)

**Comment by jstaerk** [comment]
Die Bruttorechnung ist für mich eher eine alternative Rechenmethode mit abweichendem Ergebnis, von dem ich nicht sicher bin ob sie von der EN16931-1 gedeckt ist (vgl. #144). 

Der Technical Appendix zu ZUGFeRD 2.1.1 beschreibt das rounding amount auch als "In einigen europäischen Ländern werden die ermittelten Rechnungsendbeträge z.B. auf volle 5 Cent gerundet. Die sich dadurch ergebende Differenz kann im Element RoundingAmount aus den Belegsummen abgebildet werden. Dabei sind die Rundungsregeln des jeweiligen Landes zu beachten, da diese in Europa nicht einheitlich sind.", sprich da käme beispielsweise Rappenrundung rein. 

Ich schließe den issue weil ein Workaround existiert (eigenes XML liefern) und weil es für ein Duplikat des Feature Requests in der #144 halte, wir können dort gern weitermachen.
