### ISSUE TITLE
Will XRechnung 2.0.1 be supported on July 1st?

### ISSUE THREAD

**Issue by seeeeew** [ZUGFeRD/mustangproject#243]
XRechnung 2.0.0 will only be valid until June 30th and XRechnung 2.0.1 will be valid starting July 1st. Does Mustang 2.1.1 already cover XRechnung 2.0.1? For the jump from 1.2 to 2.0 at the turn of the year the profile was automatically switched based on the date. Is that not necessary this time?
 https://github.com/ZUGFeRD/mustangproject/blob/b3846b806a2bf1b57b4f061b8ef3a467246f4228/library/src/main/java/org/mustangproject/ZUGFeRD/Profiles.java#L35

**Comment by jstaerk** [comment]
It is already supported, at least to my understanding no changes will be neccessary from what mustang supports, and the guideline ID will apparently remain the same so feel free to open an issue if you find any neccessary changes

**Comment by seeeeew** [comment]
Thanks for the fast response. This is good to hear. The unchanged ID threw me off, but otherwise I'm not aware of any need for change. I'll run a few of our invoices through the KoSIT validator after the switch, just to be sure.
