### ISSUE TITLE
Hi, is there a plan to support the 2 seller tax IDs in SellerTradeParty//SpecifiedTaxRegistration ?  

### ISSUE THREAD

**Issue by purplesword** [ZUGFeRD/mustangproject#246]
<ram:SellerTradeParty>
                <ram:Name>Bei Spiel GmbH</ram:Name>
                <ram:SpecifiedTaxRegistration>
                    <ram:ID schemeID="FC">22/815/0815/4</ram:ID>
                </ram:SpecifiedTaxRegistration>
                <ram:SpecifiedTaxRegistration>
                    <ram:ID schemeID="VA">DE136695976</ram:ID>
                </ram:SpecifiedTaxRegistration>
            </ram:SellerTradeParty>

I see there's method of `getBuyertradePartySpecifiedTaxRegistrationID` to get the VA id for buyer. But there's no method for Seller. Is there a plan to support the 2 seller tax ids?

**Comment by jstaerk** [comment]
You are referring to the interface. 
In [the invoice class](https://www.mustangproject.org/invoice-class/) you can use
```
inv.setSender(new TradeParty("Bei Spiel GmbH", "Ecke 12", "12345", "Stadthausen", "DE").addBankDetails(new BankDetails("DE88200800000970375700", "COBADEFFXXX").setAccountName("Max Mustermann")).addVATID("DE136695976").addTaxID("22/815/0815/4"))					
```
which translates into the interface as a getOwnTaxID() method I believe.
