### ISSUE TITLE
Feld BT-132 fehlt

### ISSUE THREAD

**Issue by asdf00000** [ZUGFeRD/mustangproject#247]
Für ZUGFeRD im Profil EN 16931 und XRechnung fehlt das Feld BT-132.
Dort erfasst wird die LineID der Position auf der Bestellung, die zur jeweiligen Rechnungsposition gehört (wird u.a. von der Deutschen Bahn verlangt).

Dazu müsste das Feld im `IZUGFeRDExportableItem` ergänzt werden und ab Zeile 354 im [ZUGFeRD2PullProvider](https://github.com/ZUGFeRD/mustangproject/blob/master/library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java) nach `<ram:SpecifiedLineTradeAgreement>` folgendes eingefügt werden:
<pre><code>&lt;ram:BuyerOrderReferencedDocument&gt;
  &lt;ram:LineID&gt;XXXXX&lt;/ram:LineID&gt;
&lt;/ram:BuyerOrderReferencedDocument&gt;</pre></code>

Ist es möglich, das umzusetzen?

<sub>(Wenn nötig und gewünscht, würde ich das auch selber umsetzen und versuchen, als pull request einzureichen; müsste mir das aber alles erstmal einrichten.)</sub>

**Comment by jstaerk** [comment]
Ja, das kann auf zeilenebene ergänzt werden (auf Dokumentenebene gibt es das ja schon, `getBuyerOrderReferencedDocumentID()` in IExportableTransaction), und ich kann gern helfen. Wenn es nicht dringend ist leider erst im Laufe der nächsten Woche.

Gibt es eigentlich ein Dokument oder eine Liste welche Attribute die Bahn verlangt?

**Comment by asdf00000** [comment]
[Hier](https://www.deutschebahn.com/de/geschaefte/lieferantenportal/informationsservice/rechnung-1192410) gibt es ein paar Infos von der Bahn bzgl. Anforderungen bei XRechnungen.
Bis auf das fehlende BT-132 hatte die Bahn an meiner mit Mustangproject erstellten Rechnung nichts weiter bemängelt.

Nächste Woche würde reichen, danke schon mal vorab.

**Comment by jstaerk** [comment]
Cool, danke. Der Kollege hatte sich der Sache  angenommen.

**Comment by jstaerk** [comment]
Hallo @asdf00000 
Im Master ist es wie gesagt jetzt drin, über eine kleine Mail an jstaerk at usegroup.de würde ich mich freuen, unter anderem wäre interessant wann das nächste Release gebraucht wird: ich könnte relativ schnell eine 2.2.1 machen ansonsten dauert das möglicherweise noch ein paar Wochen.

**Comment by asdf00000** [comment]
@asimkhanaup @jstaerk
Vielen Dank euch beiden.
_(Habe nicht gewusst, dass man hier auf geschlossene Issues noch antworten kann.)_
Ein baldiges Update wäre super, dann könnte ich das gleich einsetzen. Sollte es zu aufwändig sein, extra dafür eine neue Version zu machen, könnten wir uns notfalls auch noch ein paar Wochen provisorisch mit der alten Version behelfen.

**Comment by jstaerk** [comment]
Wir geben uns Mühe es mindestens zum E-Rechnungs-Gipfel aber wir haben noch andere Vorbereitungen und eine Deadline zum Ende des Monats :-/ Dürfen wir mal fragen für wen von welcher Firma wir das Feature eigentlich gerade implementiert haben? ;-)
