### ISSUE TITLE
invalid output PDF for input with incomplete CIDsets

### ISSUE THREAD

**Issue by Roman-it20one** [ZUGFeRD/mustangproject#249]
Hi!

I have a valid pdf/a-1 file "pdfa1.pdf" (according to verapdf). I combine it with a valid xml "ZUGFeRD-invoice.xml" via the command line tool.

Example of command line execution:

.\jre\bin\java.exe -jar .\lib\Mustang-CLI-2.2.1.jar --action combine --source ".\temp\pdfa1.pdf" --source-xml ".\temp\ZUGFeRD-invoice.xml" --out ".\temp\combined.pdf" --format zf --version 1 --profile T

The resulting file "combined.pdf" fails pdf/a-3 validation with the following error:

"If the FontDescriptor dictionary of an embedded CID font contains a CIDSet stream, then it shall identify all CIDs which are present in the font program, regardless of whether a CID in the font is referenced or used by the PDF or not. 

2 occurrences"

Verapdf gives this additional info:

"PDCIDFont fontFile_size == 0 \|\| fontName.search(/[A-Z]{6}\+/) != 0 \|\| CIDSet_size == 0 \|\| cidSetListsAllGlyphs == true |  
root/document[0]/pages[0](9 0 obj PDPage)/contentStream[0](16 0 obj PDContentStream)/operators[51]/font[0](UCIANL+ArialMT)/DescendantFonts[0](UCIANL+ArialMT)
root/document[0]/pages[0](9 0 obj PDPage)/contentStream[0](16 0 obj PDContentStream)/operators[128]/font[0](QUBHFO+Arial-BoldMT)/DescendantFonts[0](QUBHFO+Arial-BoldMT)"

Best Regards
Roman
[files.zip](https://github.com/ZUGFeRD/mustangproject/files/7202249/files.zip)

**Comment by jstaerk** [comment]
Thanks, I can reproduce it :-( I will have a look.

**Comment by jstaerk** [comment]
the error 
```
Rule | Status
-- | --
Specification: ISO 19005-3:2012, Clause: 6.2.11.4, Test number: 4 |  
If the FontDescriptor dictionary of an embedded CID font contains a CIDSet stream, then it shall identify all CIDs which are present in the font program, regardless of whether a CID in the font is referenced or used by the PDF or not. | Failed
2 occurrences | Hide
PDCIDFont |  
fontFile_size == 0 \|\| fontName.search(/[A-Z]{6}\+/) != 0 \|\| CIDSet_size == 0 \|\| cidSetListsAllGlyphs == true |  
root/document[0]/pages[0](7 0 obj PDPage)/contentStream[0](12 0 obj PDContentStream)/operators[298]/font[0](UCIANL+ArialMT)/DescendantFonts[0](UCIANL+ArialMT)
root/document[0]/pages[0](7 0 obj PDPage)/contentStream[0](12 0 obj PDContentStream)/operators[282]/font[0](QUBHFO+Arial-BoldMT)/DescendantFonts[0](QUBHFO+Arial-BoldMT)
```

may happen in preparedocument, may be related to https://github.com/veraPDF/veraPDF-library/issues/907
and/or
https://stackoverflow.com/questions/31209981/pdfbox-pdf-a-1a-to-pdf-a-3a

**Comment by jstaerk** [comment]
Apparently "The rules for incomplete CID sets changed between PDF/A-1a and PDF/A-3a. They are stricter in PDF/A-3a", but PDF/A-3 works completely fine without CIDsets, so the I'm now removing them. That took a bit longer because I had to clarify how to implement that in PDFBox 2.0 (https://lists.apache.org/thread.html/r5521e430803d09d5ea49a681a08051c73a691b8e325b997280b8c1b6%40%3Cusers.pdfbox.apache.org%3E) but now it works and all test files (including your file) remain PDF/A-3 valid.

**Comment by Roman-it20one** [comment]
Thank you. Great job! In the meantime i used the example for CID set removal from stackoverflow. Worked fine with our ancient pdfBox.
