### ISSUE TITLE
Wie setzte ich DespatchAdviceReferencedDocument

### ISSUE THREAD

**Issue by MarWestermann** [ZUGFeRD/mustangproject#253]
Hallo zusammen,

wir haben von unserem Partner die Vorgabe bekommen, dass wir die Lieferscheinnummer unter SupplyChainTradeTransaction.ApplicableHeaderTradeDelivery.DespatchAdviceReferencedDocument hinzufügen sollen.

Doch ich finde keine Möglichkeit hier die IssuerAssignedID zu setzen.

**Comment by jstaerk** [comment]
Hallo,
das hatte bisher leider noch niemand gebraucht, wird leider noch nicht unterstützt, zum Implementieren schnappt man sich typischerweise einen Test, erweitert den um den vorgesehenen Code, erweitert das XML manuell um Beispielcode, validiert durch und implementiert einen getter und baut das XML in ZUGFeRD2PullProvider entsprechend zusammen. Dann würde man in der Invoice-Klasse eine entsprechende Property einführen und den getter implementieren. Das hört sich komplizierter an als es ist: Wenn Sie es probieren wollen, super gern, 30min würde ich kostenlos unterstützen. Falls kommerzieller Support in Frage kommt läge das im niedrigen dreistelligen Euro-Bereich.

mit freundlichen Grüßen
Jochen Stärk

**Comment by jstaerk** [comment]
Hallo,
Gibt es einen speziellen Grund warum es gebraucht wird, bspw. eine Branchenempfehlung oder eine Verpflichtung im Rahmen der XRechnung? Es geht letzte Ende um einen Lieferscheinbezug?

Sollen wir uns bspw. Montag, 15 Uhr einfach mal auf 
 https://jochenstrk.my.webex.com/jochenstrk.my/j.php?MTID=m46a001e6aa24017edf2d488069b44691 Passwort 4hbZpiYPh93 treffen?

**Comment by seeeeew** [comment]
Das Treffen nehme ich gerne in Anspruch! Habe mir den Termin am 21.3. um 15:00 Uhr eingetragen. 

Bei uns geht es konkret darum, dass die Deutsche Bahn von ihren Lieferanten fordert, die jeweilige Lieferscheinnummer in diesem Feld zu hinterlegen. Weitere Details kann ich dann gerne am Montag erzählen. Wir können dann auch besprechen, inwiefern ich Arbeitszeit zum Mustang-Projekt beisteuern kann.

**Comment by jstaerk** [comment]
kommt in der nächsten Mustang-Version und heißt getDespatchAdviceReferencedDocumentID()

**Comment by landrix** [comment]
Man nutzt also für die Lieferscheinnummer in einer CII-XRechnung das Feld ram:DespatchAdviceReferencedDocument?
Theoretisch müsste es ja ram:DespatchAdviceReferencedDocument sein, aber das ist im Profil XRechnung nicht enthalten und ergibt eine Warnung. Kann mir jemand das bestätigen?

**Comment by jstaerk** [comment]
der technische Anhang im ZUGFeRD Infopaket sagt DeliveryNoteReferencedDocument ist nur ZF extended und nicht EN16931 und DespatchAdviceReferencedDocument scheint es auf dokumentenebene ab basic wl zu geben ja
