### ISSUE TITLE
Argument documentation -e/-t (ZUGFeRD v1)

### ISSUE THREAD

**Issue by amacado** [ZUGFeRD/mustangproject#254]
![image](https://user-images.githubusercontent.com/8781699/144093175-e9e41abc-9bb3-4e25-82f4-ebf1b65722b5.png)
https://www.mustangproject.org/kommandozeile/?lang=de & https://www.mustangproject.org/commandline/

The documentation says 
```
ZUGFeRD profile b)asic, c)omfort or e)xtended (default: e):
````

while the actual arguments for --profile are 
```
[--profile <...>]: set ZUGFeRD profile
    For ZUGFeRD v1: <B>ASIC, <C>OMFORT or EX<T>ENDED
    For ZUGFeRD v2: <M>INIMUM, BASIC <W>L, <B>ASIC, <C>IUS, <E>N16931, <X>Rechnung, EX<T>ENDED
```

Even the CLI will write 
```
Profile (b)asic, (c)omfort or ex(t)ended (default: t)
```
for ZUGFeRD v1. 

I suggest to fix the documentation with the CLI argument input of `t` for `extended`.

**Comment by jstaerk** [comment]
done, thanks
