### ISSUE TITLE
Pflichtinformationen BT-13 (Bestellreferenz) und BT-29 (Kennung des Verkäufers/Lieferantennummer)

### ISSUE THREAD

**Issue by onuryagcioglu** [ZUGFeRD/mustangproject#263]
Hallo,

wir haben die Anforderung, die Informationen zu _BT-13_ (Bestellreferenz) und _BT-29_ (Kennung des Verkäufers/Lieferantennummer) in der XRechnung anzugeben. Diese Informationen wurden bei Beauftragung mitgeteilt und werden nun in der zugehörigen Rechnung verpflichtend erwartet.

Leider konnte ich keine Möglichkeit der Übergabe dieser Informationen in der von mir aktuell eingesetzten Version 2.4.0 finden. Auch konnte ich keine entsprechenden Elemente (_Purchase order reference_ und _Seller identifier_) in der von mir verwendeten Klasse _ZUGFeRD2PullProvider_ ausmachen.

Welche Methoden wären für die Übergabe der Informationen zu nutzen bzw. falls noch nicht implementiert, wann würden diese zur Verfügung gestellt werden?

Vielen Dank im Voraus!

**Comment by jstaerk** [comment]
Hallo
BT-13, i.e. BuyerOrderReferencedDocument/IssuerAssignedID geht bspw über die Klasse(https://www.mustangproject.org/invoice-class/) per 
(item.)addReferencedDocument, BT-29, i.e. SellerTradeParty/ID ist spannenderweise noch nicht in der Contact-Klasse überschrieben, das können Sie gern implementieren (gerne PR) oder finanzieren, ansonsten können Sie alles per Interface (https://www.mustangproject.org/interface/) benutzen und überschreiben einmal kurz die IZUGFeRDExportableTradeParty.getID() für die Tradeparty die Sie per IExportableTransaction.getSender() übergeben.

mit freundlichen Grüßen
Jochen Stärk

**Comment by jstaerk** [comment]
ich korrigiere mich, für BT-29 gibt es einen setter, das müsste ungefähr so aussehen: `new invoice().setSender(new TradeParty().setID())`
