### ISSUE TITLE
How to fill out "despatch advice reference" (BT-16) in XRechnung?

### ISSUE THREAD

**Issue by seeeeew** [ZUGFeRD/mustangproject#265]
I'm trying to fill out field BT-16 "despatch advice reference" (`rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeDelivery/ram:DespatchAdviceReferencedDocument/ram:IssuerAssignedID`) in an XRechnung document, but I can't seem to find the right methods. Am I missing something or is this not implemented? Is there a way to look up which methods fill which fields?

**Comment by seeeeew** [comment]
Oops, somehow missed that this was already asked in #253. I'll see if I can implement it myself, like described in the comment.

**Comment by jstaerk** [comment]
I'll answer there :-) As regards to your request "Is there a way to look up which methods fill which fields?": not yet, but you are also not the first requestor: would you be willing to contribute or sponsor?
