### ISSUE TITLE
Unneccessary empty lines

### ISSUE THREAD

**Issue by weclapp-dev** [ZUGFeRD/mustangproject#266]
This combination 

> final OutputFormat format = OutputFormat.createPrettyPrint();
> format.setTrimText(false);

 the XMLProviders leads to additional empty lines after each xml tag.
There are three possibilities to solve:

1. Keep it like it is - the files are still valid
2. Use createCompactFormat instead of createPrettyPrint and keep the formatting in the strings to build the xml
3. Remove the formatting in building the xml tags and just let the ouputFormat do the pretty printing (favorite).

**Comment by jstaerk** [comment]
Thanks for your PR, I'll have a look, probably tomorrow. Unfortunately  the original reason why I disabled parts of the auto formatting (XRechnung #238)  does not yet have an automatic test.

**Comment by jstaerk** [comment]
what problems do I have it works like a charm
