### ISSUE TITLE
Suppress asking "Additional file attachments filename" in CLI

### ISSUE THREAD

**Issue by Kukulkano** [ZUGFeRD/mustangproject#276]
Hi,

I call it from a script and it keeps asking for additional attachments filenames?

This is my call:

```
java -jar Mustang-CLI-2.5.1.jar 
--action combine 
-format fx
-version 1 
-profile e
-out /home/kukulkano/invoicing/invoices/2022/202206-COMPANY-1157_peppol.pdf 
-source /home/kukulkano/invoicing/invoices/2022/202206-COMPANY-1157.pdf 
-source-xml /home/kukulkano/invoicing/invoices/2022/202206-COMPANY-1157.xml
```

It still asks me the following question:

**Additional file attachments filename (empty for none):**

Which switch do I have to add to suppress this question?

**Comment by Kukulkano** [comment]
I found the answer in the sourcecode:

`--attachments ""`

Maybe you can update the website at https://www.mustangproject.org/kommandozeile/?lang=de#verbose ?

**Comment by jstaerk** [comment]
updated homepage
