### ISSUE TITLE
Mustang Library provided as an Uber-Jar

### ISSUE THREAD

**Issue by gb-klein** [ZUGFeRD/mustangproject#297]
We are planning to use the mustang project as a library in our backend application and noticed that you are providing it in the form of an uber-jar (>30mb) shipping with all its transitive dependencies. One problem we are facing with that is that we use the latest slf4j version (2.x) which leads to conflicts with the version provided by mustang (although 2.x is backwards compatible with 1.x - but not vice-versa). Another issue is that we only need the importer part for now which seems to only require the org.apache.pdfbox dependencies. By building the project manually and taking only the slim jar (including pdfbox deps) we were able to get the importer part running while having a much smaller classpath footprint (~4mb opposed to >30mb). 
We would like to understand:
- What is the reason that you are providing the library as an uber-jar?
- Is there a slim version on maven central?

**Comment by gb-klein** [comment]
Ah sorry i just now saw that there where already discussions and going on and even a PR already exists

**Comment by jstaerk** [comment]
missed the answer, merged, lets try in in the next version

**Comment by jstaerk** [comment]
merged in 2.6.0
