### ISSUE TITLE
SchemeID "FC" für die Steuernummer wird von der Validierung als ungültig abgelehnt

### ISSUE THREAD

**Issue by msccip** [ZUGFeRD/mustangproject#301]
Grundsätzlich ist lt. Dokumentation die Kennung "FC" (Fiscal number) zur Kennzeichnung der Steuernummer (nicht USt-ID) erlaubt. Die Validierung bringt jedoch eine Fehlermeldung:
<error type="4" location="/*[local-name()='CrossIndustryInvoice']/*[local-name()='SupplyChainTradeTransaction']/*[local-name()='ApplicableHeaderTradeAgreement']/*[local-name()='BuyerTradeParty']/*[local-name()='SpecifiedTaxRegistration']/*[local-name()='ID']" criterion="document('FACTUR-X_EN16931_codedb.xml')//cl[@id=16]/enumeration[@value=$codeValue16]">Value of '@schemeID' is not allowed. (From /xslt/ZF_220/FACTUR-X_EN16931.xslt)</error>

Validiert man das XML mit dem KoSIT Validator, kommt keine Fehlermeldung. Warum erfolgt für ZUGFeRD hier eine Einschränkung auf "VA" ?

...
            <ram:BuyerTradeParty>
                <ram:Name>xxxx</ram:Name>
                <ram:PostalTradeAddress>
                    <ram:PostcodeCode>99999</ram:PostcodeCode>
                    <ram:LineOne>Straße 50</ram:LineOne>
                    <ram:CityName>Musterstadt</ram:CityName>
                    <ram:CountryID>DE</ram:CountryID>
                </ram:PostalTradeAddress>
                <ram:SpecifiedTaxRegistration>
                    <ram:ID schemeID="FC">47114712</ram:ID>
                </ram:SpecifiedTaxRegistration>
            </ram:BuyerTradeParty>

**Comment by jstaerk** [comment]
Hi,
that's interesting, when I tried to reproduce it with a whole file (i.e., [this one](https://github.com/ZUGFeRD/mustangproject/files/10188309/factur-x.incorrect.txt) ) in Mustang 2.5.7 I got a different error, namely
```
<error type="24" location="/*:CrossIndustryInvoice[namespace-uri()='urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100'][1]/*:SupplyChainTradeTransaction[namespace-uri()='urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100'][1]/*:ApplicableHeaderTradeAgreement[namespace-uri()='urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100'][1]/*:SellerTradeParty[namespace-uri()='urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100'][1]" criterion="(ram:ID) or (ram:GlobalID) or (ram:SpecifiedLegalOrganization/ram:ID) or (ram:SpecifiedTaxRegistration/ram:ID[@schemeID='VA'])">[BR-CO-26]-In order for the buyer to automatically identify a supplier, the Seller identifier (BT-29), the Seller legal registration identifier (BT-30) and/or the Seller VAT identifier (BT-31) shall be present. [ID BR-CO-26] from /xslt/cii16931schematron/EN16931-CII-validation.xslt)</error>
```

Please note that the upstream location to inquire at would be https://github.com/ConnectingEurope/eInvoicing-EN16931/issues and that this requirement maybe does not stop you from mentioning FC as long as you also mention e.g. a VA. To my unaided eye VA looks more like a domestic identifier and if you assume that the we're talking about EN16931 or a CIUS thereof, international rules may apply.

kind regards
Jochen

**Comment by msccip** [comment]
Hi,
when I put the "FC" below SellerTradeParty like in your example, I don't get any errors. But if I set it inside BuyerTradeParty, the schemeID is said to be invalid. And that only if I check it with Mustang.

**Comment by jstaerk** [comment]
Hi @msccip  could you please attach a file that raises the according error? Validation errors are really difficult to chase when you don't have a sample where they occur. Thank you.

**Comment by msccip** [comment]
[ZF2202000002.PDF](https://github.com/ZUGFeRD/mustangproject/files/10536119/ZF2202000002.PDF)

<?xml version="1.0" encoding="UTF-8"?>

<validation filename="ZF2202000002.PDF" datetime="2023-01-30 14:04:36">
  <pdf> 
    <report> 
      <buildInformation> 
        <releaseDetails id="core" version="1.22.2" buildDate="2022-09-14T13:46:00+02:00"/>  
        <releaseDetails id="validation-model" version="1.22.2" buildDate="2022-09-14T13:47:00+02:00"/> 
      </buildInformation>  
      <jobs> 
        <job> 
          <item size="87971"> 
            <name>D:\CIP_VFP\TEST\KOMMU_DEV\CIPRechnung\ERechAusgabe\ZF2202000002.PDF</name> 
          </item>  
          <validationReport profileName="PDF/A-3U validation profile" statement="PDF file is compliant with Validation Profile requirements." isCompliant="true"> 
            <details passedRules="126" failedRules="0" passedChecks="3081" failedChecks="0"/> 
          </validationReport>  
          <duration start="1675083876304" finish="1675083876932">00:00:00.628</duration> 
        </job> 
      </jobs>  
      <batchSummary totalJobs="1" failedToParse="0" encrypted="0" outOfMemory="0" veraExceptions="0"> 
        <validationReports compliant="1" nonCompliant="0" failedJobs="0">1</validationReports>  
        <featureReports failedJobs="0">0</featureReports>  
        <repairReports failedJobs="0">0</repairReports>  
        <duration start="1675083876198" finish="1675083876950">00:00:00.752</duration> 
      </batchSummary> 
    </report>  
    <info>
      <signature>Mustang</signature>
      <duration unit="ms">884</duration>
    </info>
    <summary status="valid"/>
  </pdf>  
  <xml>
    <info>
      <version>2</version>
      <profile>urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.2</profile>
      <validator version="2.6.0"/>
      <rules>
        <fired>8</fired>
        <failed>1</failed>
      </rules>
      <duration unit="ms">2368</duration>
    </info>
    <messages>
      <error type="4" location="/*[local-name()='CrossIndustryInvoice']/*[local-name()='SupplyChainTradeTransaction']/*[local-name()='ApplicableHeaderTradeAgreement']/*[local-name()='BuyerTradeParty']/*[local-name()='SpecifiedTaxRegistration']/*[local-name()='ID']" criterion="document('FACTUR-X_EN16931_codedb.xml')//cl[@id=16]/enumeration[@value=$codeValue16]">Value of '@schemeID' is not allowed. from /xslt/ZF_221/FACTUR-X_EN16931.xslt)</error> 
    </messages>
    <summary status="invalid"/>
  </xml>
  <messages></messages>
  <summary status="invalid"/>
</validation>

**Comment by reiz** [comment]
@msccip @jstaerk In my humble opinion the specification and the schematron rules are fine for this case. If you want to create a credit note (Gutschrift) as an e-invoice ZUGFeRD document, you have to choose the typeCode 389. In this case the `SellerTradeParty` is the contractor/freelancer and the `BuyerTradeParty` is your own company. This is because your company (`BuyerTradeParty`) is buying goods or services from the contractor/freelancer (`SellerTradeParty`). 

In this case you can use `schemeID="FC"` as `SpecifiedTaxRegistration` under the `SellerTradeParty`. On the other hand you have to use `schemeID="VA"`  as `SpecifiedTaxRegistration` under the `BuyerTradeParty`. This is because ZUGFeRD is only mandatory for B2B and as a business you should have a VAT ID. That is at least my understanding. Correct my if I'm wrong. I'm not a tax layer. Don't hold my liable for my words here! 

Here attached is valid credit note as an e-invoice ZUGFeRD document, created at [ZEIT.IO](https://zeit.io). 
It was validated by services.fnfe-mpe.org: [ZEIT.IO-CreditNote.pdf](https://github.com/user-attachments/files/16783126/ZEIT.IO-CreditNote.pdf) 

The PDF contains this XML: 

```XML
<?xml version="1.0" encoding="UTF-8"?>
<rsm:CrossIndustryInvoice xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:rsm="urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100" xmlns:qdt="urn:un:unece:uncefact:data:standard:QualifiedDataType:100" xmlns:ram="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:100">
  <rsm:ExchangedDocumentContext>
    <ram:GuidelineSpecifiedDocumentContextParameter>
      <ram:ID>urn:cen.eu:en16931:2017#compliant#urn:factur-x.eu:1p0:basic</ram:ID>
    </ram:GuidelineSpecifiedDocumentContextParameter>
  </rsm:ExchangedDocumentContext>
  <rsm:ExchangedDocument>
    <ram:ID>CN-0010</ram:ID>
    <ram:TypeCode>389</ram:TypeCode>
    <ram:IssueDateTime>
      <udt:DateTimeString format="102">20240828</udt:DateTimeString>
    </ram:IssueDateTime>
    <ram:IncludedNote>
      <ram:Content>Für die erbrachten und genehmigten Leistungen, erlauben wir uns, Ihnen folgende Position(en) gutzuschreiben.</ram:Content>
    </ram:IncludedNote>
    <ram:IncludedNote>
      <ram:Content>Bank: Deutsche Bank
IBAN: DE07 1234 1234 1234 1234 12</ram:Content>
    </ram:IncludedNote>
  </rsm:ExchangedDocument>
  <rsm:SupplyChainTradeTransaction>
    <ram:IncludedSupplyChainTradeLineItem>
      <ram:AssociatedDocumentLineDocument>
        <ram:LineID>1</ram:LineID>
      </ram:AssociatedDocumentLineDocument>
      <ram:SpecifiedTradeProduct>
        <ram:Name>Projekt: UI-TEST
Zeitraum: 01.08.2024 - 28.08.2024</ram:Name>
      </ram:SpecifiedTradeProduct>
      <ram:SpecifiedLineTradeAgreement>
        <ram:NetPriceProductTradePrice>
          <ram:ChargeAmount>75.0</ram:ChargeAmount>
        </ram:NetPriceProductTradePrice>
      </ram:SpecifiedLineTradeAgreement>
      <ram:SpecifiedLineTradeDelivery>
        <ram:BilledQuantity unitCode="HUR">4.0</ram:BilledQuantity>
      </ram:SpecifiedLineTradeDelivery>
      <ram:SpecifiedLineTradeSettlement>
        <ram:ApplicableTradeTax>
          <ram:TypeCode>VAT</ram:TypeCode>
          <ram:CategoryCode>S</ram:CategoryCode>
          <ram:RateApplicablePercent>19.0</ram:RateApplicablePercent>
        </ram:ApplicableTradeTax>
        <ram:SpecifiedTradeSettlementLineMonetarySummation>
          <ram:LineTotalAmount>300.0</ram:LineTotalAmount>
        </ram:SpecifiedTradeSettlementLineMonetarySummation>
      </ram:SpecifiedLineTradeSettlement>
    </ram:IncludedSupplyChainTradeLineItem>
    <ram:ApplicableHeaderTradeAgreement>
      <ram:BuyerReference>PO12</ram:BuyerReference>
      <ram:SellerTradeParty>
        <ram:ID>35182/02473</ram:ID>
        <ram:Name>Max Mustermann</ram:Name>
        <ram:PostalTradeAddress>
          <ram:PostcodeCode>68199</ram:PostcodeCode>
          <ram:LineOne>Otto-Beck-Str. 12</ram:LineOne>
          <ram:CityName>Mannheim</ram:CityName>
          <ram:CountryID>DE</ram:CountryID>
        </ram:PostalTradeAddress>
        <ram:URIUniversalCommunication>
          <ram:URIID schemeID="EM">z_worker@zeit.io</ram:URIID>
        </ram:URIUniversalCommunication>
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="FC">35182/02473</ram:ID>
        </ram:SpecifiedTaxRegistration>
      </ram:SellerTradeParty>
      <ram:BuyerTradeParty>
        <ram:ID>DE12345</ram:ID>
        <ram:Name>AgencyOne GmbH</ram:Name>
        <ram:PostalTradeAddress>
          <ram:PostcodeCode>68112</ram:PostcodeCode>
          <ram:LineOne>Max-Bam-Str. 23</ram:LineOne>
          <ram:CityName>Mannheim</ram:CityName>
          <ram:CountryID>DE</ram:CountryID>
        </ram:PostalTradeAddress>
        <ram:URIUniversalCommunication>
          <ram:URIID schemeID="EM">reiz@zeit.io</ram:URIID>
        </ram:URIUniversalCommunication>
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="VA">DE12345</ram:ID>
        </ram:SpecifiedTaxRegistration>
      </ram:BuyerTradeParty>
    </ram:ApplicableHeaderTradeAgreement>
    <ram:ApplicableHeaderTradeDelivery>
      <ram:ShipToTradeParty>
        <ram:PostalTradeAddress>
          <ram:CountryID>DE</ram:CountryID>
        </ram:PostalTradeAddress>
      </ram:ShipToTradeParty>
      <ram:ActualDeliverySupplyChainEvent>
        <ram:OccurrenceDateTime>
          <udt:DateTimeString format="102">20240826</udt:DateTimeString>
        </ram:OccurrenceDateTime>
      </ram:ActualDeliverySupplyChainEvent>
    </ram:ApplicableHeaderTradeDelivery>
    <ram:ApplicableHeaderTradeSettlement>
      <ram:CreditorReferenceID>DE07 1234 1234 1234 1234 12</ram:CreditorReferenceID>
      <ram:InvoiceCurrencyCode>EUR</ram:InvoiceCurrencyCode>
      <ram:SpecifiedTradeSettlementPaymentMeans>
        <ram:TypeCode>42</ram:TypeCode>
        <ram:PayerPartyDebtorFinancialAccount>
          <ram:IBANID>DE07 1234 1234 1234 1234 12</ram:IBANID>
        </ram:PayerPartyDebtorFinancialAccount>
      </ram:SpecifiedTradeSettlementPaymentMeans>
      <ram:ApplicableTradeTax>
        <ram:CalculatedAmount>57.0</ram:CalculatedAmount>
        <ram:TypeCode>VAT</ram:TypeCode>
        <ram:BasisAmount>300.0</ram:BasisAmount>
        <ram:CategoryCode>S</ram:CategoryCode>
        <ram:RateApplicablePercent>19.0</ram:RateApplicablePercent>
      </ram:ApplicableTradeTax>
      <ram:SpecifiedTradePaymentTerms>
        <ram:Description>Zahlungsziel 30 Tage.</ram:Description>
        <ram:DueDateDateTime>
          <udt:DateTimeString format="102">20240927</udt:DateTimeString>
        </ram:DueDateDateTime>
      </ram:SpecifiedTradePaymentTerms>
      <ram:SpecifiedTradeSettlementHeaderMonetarySummation>
        <ram:LineTotalAmount>300.0</ram:LineTotalAmount>
        <ram:TaxBasisTotalAmount>300.0</ram:TaxBasisTotalAmount>
        <ram:TaxTotalAmount currencyID="EUR">57.0</ram:TaxTotalAmount>
        <ram:GrandTotalAmount>357.0</ram:GrandTotalAmount>
        <ram:DuePayableAmount>357.0</ram:DuePayableAmount>
      </ram:SpecifiedTradeSettlementHeaderMonetarySummation>
    </ram:ApplicableHeaderTradeSettlement>
  </rsm:SupplyChainTradeTransaction>
</rsm:CrossIndustryInvoice>
```

This ticket is related to [this ZUGFeRD Community ticket](https://www.zugferd-community.net/forum/viewtopic.php?p=463#p463)

**Comment by jstaerk** [comment]
Hello,

to me it seems as if both your, @msccip and your, @reiz file validate as correct on 2.13.0 so just for my understanding, you suggest to change what where?

kind regards
Jochen

**Comment by msccip** [comment]
the error is still there with version 2.13:

<error type="4" location="/*[local-name()='CrossIndustryInvoice']/*[local-name()='SupplyChainTradeTransaction']/*[local-name()='ApplicableHeaderTradeAgreement']/*[local-name()='BuyerTradeParty']/*[local-name()='SpecifiedTaxRegistration']/*[local-name()='ID']" criterion="document('FACTUR-X_EN16931_codedb.xml')//cl[@id=16]/enumeration[@value=$codeValue16]">Value of '@schemeID' is not allowed. from /xslt/ZF_221/FACTUR-X_EN16931.xslt)</error>

[zugferd-invoice.txt](https://github.com/user-attachments/files/17043146/zugferd-invoice.txt)

**Comment by PhilippGoetje** [comment]
> zf2.3 technical appendix to en16931, page 31 seems to indicate it **has** to be VA? ![image](https://private-user-images.githubusercontent.com/3964386/373193167-2571300f-05bb-470e-afea-6d4c2625d5fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5MTMxNzksIm5iZiI6MTczNTkxMjg3OSwicGF0aCI6Ii8zOTY0Mzg2LzM3MzE5MzE2Ny0yNTcxMzAwZi0wNWJiLTQ3MGUtYWZlYS02ZDRjMjYyNWQ1ZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDNUMTQwMTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGE2ZDM3ODc3NmVhMWQ1MjIzYTc5ZTNmY2UwZDQ0MWE3YmUwOGE2M2IzODM5NDAzZDZiMDllNDNjNjAwMTM1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Zpl6wJq5B8PgQgl6dNsjJcUgTw7KT0093zy1kyTQ6RQ)

I know that Mustang is not responsible for the standards, yet this is developing into an issue. 
When I, a business, want to write an invoice to a "Kleinunternehmer", which is only using a taxID, the resulting invoice is invalid, due to "Value of '@schemeID' is not allowed." when submitting a "<ram:ID schemeID="FC">123456789</ram:ID>" line. 
While I understand that e-Invoices are intended for B2B, the other trade party is a business, just a "small" one. 

Can someone please present this in the appropirate channels of the standard-forming circle?
Thanks!

**Comment by IsThatUniqueEnough** [comment]
@PhilippGoetje Why do you think you need to provide a "FC" for the buyer instead of simply omitting the tax registration if you don't know it? There are business rules that require a "VA" for the buyer in some cases but are there legal use cases that would really require a "FC"?

**Comment by PhilippGoetje** [comment]
> @PhilippGoetje Why do you think you need to provide a "FC" for the buyer instead of simply omitting the tax registration if you don't know it? There are business rules that require a "VA" for the buyer in some cases but are there legal use cases that would really require a "FC"?

Well, I do know the taxID, so if I know it, I must actively omitt the taxID to get a valid invoice, instead of simply submitting it?
While I do get a valid invoice, this is not only confusing but also kind of misleading. I am still of the opinion that the transfer of a taxID alone should be valid and the BR that require a vatID should only check the vatID depending on the requirements of these specific BRs. I belive an "invalid" invoice because I do not violate any rules (from the users perspective) is wrong and should be addressed. 
Since I do not have access to the standards committee (or dont know where to post this issue) I would kindly request somebody to relay this issue forward. Thanks!

**Comment by archdev-de** [comment]
I discussed this with my inhouse tax advisor. The ID, which is marked as FC, is the ID that everyone receives from the tax office when they start their business. The VAT ID is applied for additionally for trading across borders for the purpose of VAT accounting.

The definition in EN16931 is inconsistent. Here, the IDs in SpecifiedTaxRegistration (VA = BT-31 / FC = BT-32) are interchangeable, but in the business rule BR-CO-26, the FC (BT-32) option is missing."

Additional Notes

- FC likely stands for "Finanzamt-Kennung" (tax office ID) or a similar term.
- VA likely stands for "VAT-Kennung" (VAT ID).
- EN16931 refers to the European standard for electronic invoicing.
- BT-31 and BT-32 are likely identifiers for specific data elements within the EN16931 standard.
- BR-CO-26 probably refers to a specific business rule within the EN16931 standar
