### ISSUE TITLE
Extend constructor for streaming /library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDInvoiceImporter.java

### ISSUE THREAD

**Issue by MCl57** [ZUGFeRD/mustangproject#314]
Is it possible to add a constructor to the 'ZUGFeRDInvoiceImporter' class?

file: /library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDInvoiceImporter.java

```java
import java.io.IOException;

public ZUGFeRDInvoiceImporter(InputStream stream) {
		super(stream);
}

```

**Comment by jstaerk** [comment]
had been added by michael clausohm on 19.04 already
