### ISSUE TITLE
Is ZUGFeRD outdated with regard to german tax law in 2023?

### ISSUE THREAD

**Issue by psynetic** [ZUGFeRD/mustangproject#319]
Error message:
"[BR-S-05]-In an Invoice line (BG-25) where the Invoiced item VAT category code (BT-151) is "Standard rated" the Invoiced item VAT rate (BT-152) shall be greater than zero."

But since 2023 the pos 87 in the german UStVA-formular is standard tax rate ("S") with zero percent tax (e.g. photovoltaik):

![grafik](https://user-images.githubusercontent.com/119499591/236009147-654aa700-379d-43f5-8633-55c19ec283e9.png)

**Comment by jstaerk** [comment]
I guess you could use Z=zero rated or E=Exempt as category code?  In ZUGFeRD that's perfectly possible (2. FACTUR-X 1.0.06 Technischer-Anhang pg 55), I believe Mustang even automatically switches to Z when you set it to 0 in the invoice (resp. product) class?
