### ISSUE TITLE
XRechnung version 2.3 used, but not valid yet

### ISSUE THREAD

**Issue by seeeeew** [ZUGFeRD/mustangproject#329]
After upgrading from Mustang 2.5.1 to 2.7.1 our XRechnung invoices got rejected by the recipient, because XRechnung version 2.3 is already used, even though it's not valid until 2023-08-01. I solved this in our software by using `new Profile("XRECHNUNG", "urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.2")` instead of `Profiles.getByName("XRechnung")` if it's before 2023-08-01, but it would be more convenient if the latter would automatically return the currently valid version. I'm pretty sure I remember this being the case in the past.

**Comment by jstaerk** [comment]
Hi,
I'm not sure if the error is on our side: do they reject it? And why?

One could argue
-  there were no significant changes to the spec (changelog: extension of the extension profile and some editorial amendments)
- there were *really* no changes, apart from the version number, as you mentioned, the XML is bitwise identical
- *they* wrote the spec, published it, along with validation artefacts, and announced it to become mandatory
- the spec is supposed to be a CIUS, i.e. a requirement specification, not a format specification (which is the reason why it's actually mapped to the two eligible formats, UBL and CII)
- plus one could argue that the fragment identifier is optional anyway and governments are, by 2014/55/EU, legally obliged to accept any valid EN16931 invoice, matching national requirements, disregarding the fragment identifier.

At least the situation has improved and while their specs used to be valid only for six month they seem to have changed to an annual cycle.

**Comment by msccip** [comment]
No invoice portal currently accepts XRechnung 2.3. At least there is a warning. But most (e.g. ZUGFeRD Community(!), Bavaria or the OZG-RE) reject them as faulty because version 2.3 is not yet recognized. Before August 1st, 2023 nobody should send XRechnung with version 2.3.

**Comment by seeeeew** [comment]
@jstaerk I agree with everything you said, unfortunately at least Deutsche Bahn doesn't, and they're pretty big. They reject invoices with 2.3, but accept the same invoice with only the version changed to 2.2. When validating the 2.3 invoice I only get a warning, but for DB that's apparently enough to reject it.

**Comment by asdf00000** [comment]
I can confirm what seeeeew wrote.
They run their automatic validators on all invoices and reject them, no matter how trivial the error is.
It would be great when the XRechnung-version was mentioned in the [History.md](https://github.com/ZUGFeRD/mustangproject/blob/master/History.md) for every future release (ideally with a warning, if that version is not yet officially "allowed".

**Comment by jstaerk** [comment]
thats a good idea I dont know if I remember to mention it every time but at least when something changes...
