### ISSUE TITLE
integrate Logging Framework 

### ISSUE THREAD

**Issue by dovogt** [ZUGFeRD/mustangproject#34]
Could a logging framework be integrated? In some places, errors are caught. As return value, there is then true or false and one does not recognize the actual error:

org.mustangproject.ZUGFeRD.ZUGFeRDExporter.getA1ParserValidationResult (PreflightParser)

**Comment by jstaerk** [comment]
Yes, please note that due to third party libraries we already have a _depency_ on Apache Commons Logging, so one could try if that works and start using it

**Comment by dovogt** [comment]
In the pom.xml I can not find a registered dependency to Apache Common Logging. Which does not matter, I would like in the places log outputs

**Comment by dovogt** [comment]
Oh, sorry. I just see that the dependency comes across the PDFBox. Then I can use this.
