### ISSUE TITLE
FreeSans.ttf at two locations in the library.jar

### ISSUE THREAD

**Issue by pokint** [ZUGFeRD/mustangproject#358]
I've noticed that the library.jar grew from 400 KB to 3,8 MB (version 2.8 vs 2.10). The reason seems to be the new fonts (FreeSans), which is OK, but you can find one ttf-file twice in the jar e.g. you can find FreeSans.ttf in the root and under src/main. Is this required?

**Comment by jstaerk** [comment]
Actually no, they are not required, I had been working on a feature to visualize xml into pdf but the feature did not yet make it and the files were not cleanly removed, thanks for spotting
