### ISSUE TITLE
404 for example PDF

### ISSUE THREAD

**Issue by reiz** [ZUGFeRD/mustangproject#360]
The README.md references a PDF document as documentation. In that PDF, on page 2, there is a reference to this `http://www.mustangproject.org/MustangGnuaccountingBeispielRE-
 2017 1118 _50 6 blanko.pdf` document, which does not exist.

**Comment by jstaerk** [comment]
done (/files/ was missing in the path) but that is the pre-2.0 pre-relaunch doc, the doc on how to develop *on* mustang is now 
https://github.com/ZUGFeRD/mustangproject/blob/master/doc/development_documentation.md and the doc how to develop *with* mustang is now https://www.mustangproject.org/use/ https://www.mustangproject.org/interface/ and https://www.mustangproject.org/invoice-class/ + I'm working on Antora docs for some other project, I definitely need someone to consolidate this all together, can you help?

**Comment by reiz** [comment]
I confirm, it's fixed now! Thx for the fast turn around! 

I don't want to give you a commitment, which I can't hold. I just become a dad, a couple months ago. Nights are short and I work less now than before the birth. But I will look into the project and help where I can.
