### ISSUE TITLE
Problem with Validation of X-Rechnung

### ISSUE THREAD

**Issue by asdf00000** [ZUGFeRD/mustangproject#368]
When there are no allowances per line-item, `GrossPriceProductTradePrice` should not be included into the xml.

If included, the Validators show the following error-messages:

Mustang-Validator Mustang-CLI-2.10.0:
```
ERROR org.mustangproject.validator.ZUGFeRDValidator - Error 27: Item net price MUST equal (Gross price - Allowance amount) when gross price is provided. [ID PEPPOL-EN16931-R046] from /xslt/XR_30/XRechnung-CII-validation.xslt)
```

KOSIT-Validator using validator-configuration-xrechnung_3.0.1_2023-09-22:
```
Item net price MUST equal (Gross price - Allowance amount) when gross price is provided.
--
Pfad: /rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction[1]/ram:IncludedSupplyChainTradeLineItem[2]/ram:SpecifiedLineTradeAgreement[1]/ram:GrossPriceProductTradePrice[1]
```

I committed a suggestion to fix this.

**Comment by jstaerk** [comment]
I had hoped they would fix this nonsense https://github.com/itplr-kosit/validator-configuration-xrechnung/issues/84

**Comment by jstaerk** [comment]
but I merged your PR, thanks
