### ISSUE TITLE
Continuous integration server

### ISSUE THREAD

**Issue by yankee42** [ZUGFeRD/mustangproject#37]
Setting up a continuous integration server could reduce the risk of merging changes that do not build or that build only one some developers machines.

For OpenSource there are many free services, such as [Travis-CI](https://travis-ci.org/) or [CircleCI](https://circleci.com/). They integrate with github, so that the build status can be displayed for each PR etc. Setup is incredibly easy.

What do you think?

**Comment by jstaerk** [comment]
I don't think I need it (I was just too silly not to try to compile after a merge, I should be able to do better next time) but I would not object, in particular if it helped with the maven deployment

**Comment by yankee42** [comment]
If you configure maven accordingly, then the CI server can also automatically deploy artificats to a maven repository.

Of course you can get along without a CI, but in my experience it is very helpful nevertheless and has noi disadvantages. Especially with such a simple project as this one it is pretty much "auto-discover all settings and just build it" and it should work. Setup should not take more than a minute or two :-). But you'd be the one that needs to do the setup, because of the permissions on Github.

Anyway: In case decide to try and have any questions, I'll be glad to have a look.

**Comment by skleinealber** [comment]
I think an CI would be great, for building two types of this project (one library without the included dependencies, and one standalone version with all dependencies included).
Afaik the use (of Travis) is free of charge for open-source projects like this one.

**Comment by jstaerk** [comment]
Closed because apparently nobody volunteers to do it
