### ISSUE TITLE
Jakarta Support

### ISSUE THREAD

**Issue by paulsen-it** [ZUGFeRD/mustangproject#372]
Please implement a Jakarta Version from MustangProject

**Comment by jstaerk** [comment]
Whats the advantage? And what would *you* need to implement it?

**Comment by paulsen-it** [comment]
We use Spring Boot and in the latest version Spring Boot has been changed to Jakarta. As a result, I have problems integrating the Mustang Project. Because a mixture of Javax and Jakarta causes complications.

**Comment by Sarenor** [comment]
@paulsen-it if you're just running the mustang library without the validator I didn't need to do much to make it compatible.
If you need to run the validator as well you can override a lot of the mustang dependencies with their Jakarta equivalent to make it work (excuse the gradle format):
```groovy
  // Mustang Dependencies
  implementation group: 'xerces', name: 'xercesImpl', version: xercesVersion
  implementation 'org.xmlunit:xmlunit-assertj:2.8.2'
  implementation group: 'org.mustangproject', name: 'validator', version: mustangVersion
  // Dependencies necessary to run the mustang validator in SB 3+ & Java 11+
  implementation group: 'org.verapdf', name: 'core-jakarta', version: '1.24.2'
  implementation group: 'org.verapdf', name: 'parser', version: '1.24.1'
  implementation group: 'org.verapdf', name: 'feature-reporting', version: '1.24.2'
  implementation group: 'org.verapdf', name: 'validation-model', version: '1.24.2'
  implementation group: 'org.verapdf', name: 'metadata-fixer', version: '1.24.2'
  implementation group: 'com.helger.schematron', name: 'ph-schematron-xslt', version: '8.0.0'
  implementation group: 'com.helger.schematron', name: 'ph-schematron-api', version: '8.0.0'
  implementation group: 'com.helger.commons', name: 'ph-jaxb', version: '11.1.6'
  ```

**Comment by phax** [comment]
The benefit is, that you get maintained artifacts. After moving "JavaEE" to the Eclipse Foundation, they were forced to change the namespaces from `javax.*` to `jakarta.*`.
So using `javax.*` is like riding a dead horse - it has no future.
However, the switch to Jakarta requires to update to JAXB 4, minimum Java 11 etc.
As an author of some of these dependencies, I am not convinced the simple replacement is a suitable long term solution....

**Comment by Sarenor** [comment]
I completely agree with that but there isn't much choice when you have to make it work _now_, sadly.

**Comment by phax** [comment]
I created a fork and the changes are more then just dependency updates. Working on the tests and will create a PR when ready

**Comment by phax** [comment]
Initial proposal in #393 - depends also on #373

**Comment by phax** [comment]
Part of the [2.12.0](https://github.com/ZUGFeRD/mustangproject/releases/tag/core-2.12.0) release
