### ISSUE TITLE
Upgrade to PDFBox 3

### ISSUE THREAD

**Issue by jstaerk** [ZUGFeRD/mustangproject#373]

**Comment by jstaerk** [comment]
no more compile errors, now fixing the tests

**Comment by odi78** [comment]
good issue - any release plannings for this?

**Comment by jstaerk** [comment]
I would like to have it in the next release, 2.12. 

But it depends a bit how it behaves and how other people act. If there e.g. were a new ZUGFeRD release in june I might want to follow up with a new mustang version in maybe the two weeks thereafter.

The test output is currently
```
[ERROR] Tests run: 70, Failures: 9, Errors: 15, Skipped: 0
```
And the pdf input pre-validation is now stricter. If it weren't we would be down at 7 Failures 11 Errors. One plan is to remove the input pre-validation from the "library" component altogether, but leave it in the "validator" component. In which case it could be verapdf based, which would at least remove the puzzling effects that occur when the pdfbox based input validation reports different errors than the (often better) verapdf based "output" validation.

But there's also different things, PDF files which could previously be read and now seem to be no longer understood. I'm investigating...

**Comment by odi78** [comment]
I understand. If I can help you with testing some PDF files with PDF Box 3.x, I've tons of PDFs from different ERP Systems like SAP, NAV, BC, Lexoffice, ...

**Comment by phax** [comment]
Initial proposal in #393

**Comment by jstaerk** [comment]
What do you mean initial proposal? You must have spend days, that fixed the whole project and maybe more #372 #337

**Comment by phax** [comment]
Part of the [2.12.0](https://github.com/ZUGFeRD/mustangproject/releases/tag/core-2.12.0) release
