### ISSUE TITLE
ClassCastException: ZUGFeRDExporterFromA3 cannot be cast to ZUGFeRDExporterFromPDFA

### ISSUE THREAD

**Issue by langfr** [ZUGFeRD/mustangproject#389]
When using
            `IZUGFeRDExporter ze = new ZUGFeRDExporterFromPDFA();`
then
`            ze.setProfile( Profiles.getByName( "extended" ) );`
leads to a class cast exception:
```Caused by: java.lang.ClassCastException: org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromA3 cannot be cast to org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromPDFA
	at org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromPDFA.setProfile(ZUGFeRDExporterFromPDFA.java:151)
	at org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromPDFA.setProfile(ZUGFeRDExporterFromPDFA.java:40)
	at biz.mbisoftware.fn.ejb.session.sales.InvoiceExport.buildInvoiceZugferdPdf(InvoiceExport.java:523)
	at biz.mbisoftware.fn.ejb.session.sales.InvoiceExport.processInvoice(InvoiceExport.java:403)
```

**Comment by msccip** [comment]
I get the opposite message with version 2.12.0: ...FromPDFA cannot be cast to class ...FromA3

class org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromPDFA cannot be cast to class org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromA3 (org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromPDFA and org.mustangproject.ZUGFeRD.ZUGFeRDExporterFromA3 are in unnamed module of loader 'app')

**Comment by langfr** [comment]
Please create a new issue.
Where does this Exception exactly happen ? Main.java:726 ? The complete stacktrace would be helpful.
Share the command line you're using, so that somebody is able to reproduce this issue. java -jar Mustang-CLI-2.12.0.jar .... ?
