### ISSUE TITLE
CLI: action combine: --ignorefileextension to ignore PDF/A input file errors dosen't work

### ISSUE THREAD

**Issue by joergenp** [ZUGFeRD/mustangproject#392]
when combining a pdf (created as PDF/A-1b with Libre Office) with a xml the CLI throws 
_ERROR ROOT - File is not a valid PDF/A-1 input file_
independent of option --ignorefileextension.

By looking at the source I can see that .load(pdfName) ist called before .ignorePDFAErrors() (code line 715-728):

```
				ze = new ZUGFeRDExporterFromPDFA().load(pdfName);

					ze.setProducer("Mustang-cli")
					.setZUGFeRDVersion(zfIntVersion)
					.setCreator(System.getProperty("user.name")).setProfile(zfConformanceLevelProfile);
				if (ignoreInputErrors) {
					((ZUGFeRDExporterFromA1) ze).ignorePDFAErrors();
				}
			}
			for (FileAttachment attachment : attachments) {
				((ZUGFeRDExporterFromA3) ze).attachFile(attachment.getFilename(), attachment.getData(), attachment.getMimetype(), attachment.getRelation());
			}

//			ze = ze.load(pdfName);
```

Seems this was introduced on #341

**Comment by jstaerk** [comment]
I added a test for the functionality itself in [d22a8a0] , unfortunately I cant test end-to-end yet due to a Exception in thread "main" java.lang.NoClassDefFoundError: jakarta/activation/DataSource... I hope I can fix that soon
