### ISSUE TITLE
Build succeeds but file is unusable on alpine/docker

### ISSUE THREAD

**Issue by Haui1112** [ZUGFeRD/mustangproject#397]
Hi, thank you for making this! I'm trying to essentially make a runner that builds the app from source and outputs it. Sadly, the output is not usable as of now:

## Error
```
"Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.slf4j.Logger.error(String, java.lang.Throwable)" because "org.mustangproject.commandline.Main.LOGGER" is null
        at org.mustangproject.commandline.Main.main(Main.java:442)"
```
and
```
no main manifest attribute, in original-Mustang-CLI-3.0.0-SNAPSHOT.jar
```

## Expected behavior
The app runs normally

## Steps to reproduce
1. sudo docker run --rm -it alpine
2. apk add openjdk21 maven git --no-cache && \
git clone https://github.com/ZUGFeRD/mustangproject.git && \
cd mustangproject && \
mvn clean install
3. cd Mustang-CLI/target
4. java -jar Mustang-CLI-3.0.0-SNAPSHOT.jar
5. see error "Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.slf4j.Logger.error(String, java.lang.Throwable)" because "org.mustangproject.commandline.Main.LOGGER" is null
        at org.mustangproject.commandline.Main.main(Main.java:442)"
6. java -jar original-Mustang-CLI-3.0.0-SNAPSHOT.jar
7. see error "no main manifest attribute, in original-Mustang-CLI-3.0.0-SNAPSHOT.jar"

**Comment by jstaerk** [comment]
thanks I just fixed that. However, the master is not yet stable, maybe you rever to the branch of a release version?
