### ISSUE TITLE
setter based API

### ISSUE THREAD

**Issue by jstaerk** [ZUGFeRD/mustangproject#40]
Currently one has to provide classes with partially difficult interfaces in order to export the XML for a ZUGFeRD file. This could also be done with setters, so that one can create a invoice with something like 

```
ZUGFeRDProduct zp=new ZUGFeRDProduct();
zp.setText("Something").setUnit("C61").setCurrency("EUR").setPrice(123);
ZUGFeRDItem zit=new ZUGFeRDItem();
zit.setQuantity(5).setProduct(zp);
ZUGFeRDInvoice zin=new ZUGFeRDInvoice();
zi.addItem(zit);

```

**Comment by skleinealber** [comment]
What about copying the interface implementations of [the test directory](https://github.com/ZUGFeRD/mustangproject/tree/master/src/test/java/org/mustangproject/ZUGFeRD) to the main directory?
They seem to fit perfectly in this case of enhancement.
Maybe one could change the names of the implementations from `IZUGFeRDAllowanceChargeImpl` to something shorter like `ZCharge`/`ZUGFeRDCharge`.
