### ISSUE TITLE
Zugferd Importer throws exception for French Invoice when extracting Zugferd Version

### ISSUE THREAD

**Issue by Sarenor** [ZUGFeRD/mustangproject#401]
This code in ``getVersion()`` throws an exception for a french Invoice I recently stumbled across:
```java
		if (head.contains("<rsm:CrossIndustryDocument") //
			|| head.contains("<CrossIndustryDocument") //
			|| head.contains("<SCRDMCCBDACIDAMessageStructure") //
			|| head.contains("<rsm:SCRDMCCBDACIOMessageStructure")) { //
			version = 1;
		} else if (head.contains("<rsm:CrossIndustryInvoice")) {
			version = 2;
		} else {
			throw new Exception("ZUGFeRD version could not be determined");
		}
```
because the head for the Invoice contains this:
```xml
<ns3:CrossIndustryInvoice xmlns="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:100" xmlns:ns2="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100" xmlns:ns3="urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100" xmlns:ns4="urn:un:unece:uncefact:data:standard:QualifiedDataType:100">
    <ns3:ExchangedDocumentContext>
        <ns2:GuidelineSpecifiedDocumentContextParameter>
            <ns2:ID>urn:cen.eu:en16931:2017#conformant#urn:factur-x.eu:1p0:extended</ns2:ID>
        </ns2:GuidelineSpecifiedDocumentContextParameter>
    </ns3:ExchangedDocumentContext>
```
As far as I can tell, this _should_ be a valid Zugferd 2 but the version detection code doesn't recognize it because of the namespace prefixes.

**Comment by jstaerk** [comment]
which is correct because the namespace prefixes are fixed in CII (https://www.zugferd-community.net/de/infothek/technical_xml_regarding_fixed_namespace_prefixes_rsm_ram_) and yours is wrong :-(

**Comment by Sarenor** [comment]
Sadly Page not Found but very good to know. Thank you and sorry for the unnecessary issue!

**Comment by jstaerk** [comment]
apologies here is the [corrected link](https://www.zugferd-community.net/de/infothek/technical_xml_regarding_fixed_namespace_prefixes_rsm_ram_)
