### ISSUE TITLE
make it leaner

### ISSUE THREAD

**Issue by jstaerk** [ZUGFeRD/mustangproject#402]
Evtl. könnte die Klasse die Apache FOP braucht in ein eigenes Submodul  ausgelagert werden - dann werden die Dependencies um FOP und Batik reduziert - das macht es schlanker

Und im Validator würde ich "logback" entfernen - jeder soll seine eigene Log-Implementierung verwenden können. Im pom steht "because ph-schematron needs it" (ca.) aber das stimmt nicht, Ich mach alles nur mit SLF4J

**Comment by phax** [comment]
Part of the [2.12.0](https://github.com/ZUGFeRD/mustangproject/releases/tag/core-2.12.0) release
