### ISSUE TITLE
Invoice extracted from CII XML returns only one IBAN (BT-84) although there are more

### ISSUE THREAD

**Issue by melo0187** [ZUGFeRD/mustangproject#408]
Given a CII XML file from [itplr-kosit/xrechnung-testsuite](https://github.com/itplr-kosit/xrechnung-testsuite/blob/master/src/test/business-cases/standard/01.05a-INVOICE_uncefact.xml) when extracting an Invoice with `org.mustangproject.ZUGFeRD.ZUGFeRDInvoiceImporter#extractInvoice` and accessing `org.mustangproject.TradeParty#getBankDetails` through `org.mustangproject.Invoice#getSender` then only one `org.mustangproject.BankDetails` object is returned.

Because the CII XML actually contains `PayeePartyCreditorFinancialAccount` twice (each within its own `SpecifiedTradeSettlementPaymentMeans`), I would have expected `invoice.getSender().getBankDetails()` to return a list with two `org.mustangproject.BankDetails` objects.

**Comment by melo0187** [comment]
@jstaerk excited to see this has been fixed. Any ETA for the next release that ships with this fix?

**Comment by jstaerk** [comment]
Hi, this should be released in the meanwhile?

**Comment by melo0187** [comment]
> Hi, this should be released in the meanwhile?

I can confirm that it was. Thank you!
