### ISSUE TITLE
ActualDeliverySupplyChainEvent->OccurrenceDateTime should not generally be a mandatory field for ZUGFeRD 2 invoices

### ISSUE THREAD

**Issue by erras-it** [ZUGFeRD/mustangproject#411]
ActualDeliverySupplyChainEvent->OccurrenceDateTime should not generally be a mandatory field for ZUGFeRD 2 invoices. Except for the minimum profile, an IllegalStateException is currently thrown if IExportableTransaction.getDeliveryDate() returns null (ZUGFeRD2PullProvider Line 554).

Reference: 
https://github.com/ZUGFeRD/mustangproject/blob/c88ec268f5f3c9646828a7c0931cb103251cf822/library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java#L554

**Comment by jstaerk** [comment]
done in master, will be part of the next release, thanks
