### ISSUE TITLE
SpecifiedTradeAllowanceCharge is added incorrectly

### ISSUE THREAD

**Issue by melo0187** [ZUGFeRD/mustangproject#414]
I have run a test with `zugferd/EXTENDED/EXTENDED_Fremdwaehrung.pdf` from the ZUGFeRD 2.2 info package and have noticed that allowances from `SpecifiedTradeAllowanceCharge` are added together from both `ApplicableHeaderTradeSettlement` (document level) and `SpecifiedLineTradeSettlement` (item level).

Seems wrong to me, because allowances at item level are already included in the calculation of the LineTotalAmount, so they are already part of the the item total of the invoice and must not be applied to the item total again.

This behavior in combination with the above mentioned invoice PDF document results in `org.mustangproject.ZUGFeRD.ZUGFeRDInvoiceImporter#extractInvoice` throwing the `ParseException` "Could not reproduce the invoice, this could mean that it could not be read properly".

**Comment by jstaerk** [comment]
Hi,
I'll close this because Mustang is not responsible for AWV/FeRD example files, feel free to report there but what do you make of the fact that the file not only passes ZUGFeRD but also CEN validation schematrons?
Have you checked vis á vis [EN16931](https://www.beuth.de/en/standard/din-en-16931-1/314992770)?

kind regards
Jochen

**Comment by melo0187** [comment]
@jstaerk thanks for your reply!
All I have as contact to AWV is their info@ address and my question went unanswered so far.

I am afraid I need more help to understand what you are pointing to when referring to the validations and the EN 16931.
I mean yes, the document passes ZUGFeRDValidator's validation. This is what I verified.

Do you say the document is actually in a wrong format and should be rejected?
Because if so, I would need help understanding why.
As far as I can see in EN 16931 it is pointed out that allowances on item level are already included in line item's net amount.

I opened this issue, because I suspected that the document is valid and the calculation performed in `org.mustangproject.ZUGFeRD.ZUGFeRDInvoiceImporter#extractInvoice` is wrong and so the thrown ParseException unjustified.
Do you disagree?

For the record: Your link to [DIN EN 16931](https://www.beuth.de/en/standard/din-en-16931-1/314992770) points to the superseded version. The current version is [here](https://www.dinmedia.de/en/standard/din-en-16931-1/327729047).

**Comment by jstaerk** [comment]
Hi
>Do you say the document is actually in a wrong format and should be rejected?
I say if it passes validation one should assume it's valid

>org.mustangproject.ZUGFeRD.ZUGFeRDInvoiceImporter#extractInvoice is wrong
Throwing this exception it is not wrong, it merely means that the invoice is using a feature which is not yet implemented. If you know which feature it is, and which features you need (why?), feel free to request them.

kind regards
Jochen
