### ISSUE TITLE
Support reasonCode in Allowances and Charges.

### ISSUE THREAD

**Issue by langfr** [ZUGFeRD/mustangproject#431]
Support reasonCode in Allowances and Charges.
See PR #432

**Comment by langfr** [comment]
Tested the first invoice having special discounts on item level. Using XRechnung-profile
    <ram:GuidelineSpecifiedDocumentContextParameter>
      <ram:ID>urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0</ram:ID>
    </ram:GuidelineSpecifiedDocumentContextParameter>

Surprisingly I got validation errors:
```
Funktion 'InvoiceExportXRechnung' mit Fehler beendet. 
error: [CII-SR-127] - ReasonCode should not be present [ID CII-SR-127] from /xslt/cii16931schematron/EN16931-CII-validation.xslt) 
error: [CII-SR-127] - ReasonCode should not be present [ID CII-SR-127] from /xslt/cii16931schematron/EN16931-CII-validation.xslt) 
error: [CII-SR-127] - ReasonCode should not be present [ID CII-SR-127] from /xslt/cii16931schematron/EN16931-CII-validation.xslt) 
```
Same when using Reason and not ReasonCode: [CII-SR-128] - Reason should not be present

Looking at the document 
Spezifikation Standard XRechnung
CIUS und Extension
Version XRechnung 3.0.2
Veröffentlicht 20.06.2024

both can be used, similar to the document level allowances where it's working using mustangproject validator:

<img width="770" alt="image" src="https://github.com/user-attachments/assets/446a9e0c-5ef6-4140-8c6d-3a9829661679">



Validating a document with only document level allowances on site https://www.epoconsulting.com/erechnung-sap/xrechnung-validator also these are not valid, e.g.:

<img width="914" alt="image" src="https://github.com/user-attachments/assets/73ab514a-538f-4143-848b-c53f488df070">

**Comment by jstaerk** [comment]
thanks
