### ISSUE TITLE
Validation result is invalid: problem "DeviceCMYK shall only be used if a device independent"

### ISSUE THREAD

**Issue by vmario89** [ZUGFeRD/mustangproject#433]
Hi,

i am using mustang cli on two different servers to create ZUGFeRD PDF invoices from PDF/A-3 files in conjunction with XML e-invoice. This works fine on the one machine, but has some issue on the other machine (one has Windows 10 Pro and works as home server; the other machine is a Windows 2019 Server). I have no clue whats the reason.

The first step is to create that ZUGFeRD invoice with mustang, the second step is to validate the new invoice with mustang to get status info about.

I am using mustang cli version `2.11.0`

the creation is done with python which works well. it includes the settings i use to create the PDF. The input PDF invoice comes from JTL WaWi 1.9.4.6 and is created with PDF/A-3 format (otherwise mustang would complain and stop creating ZUGFeRD)

```
                    cmd_mustang_combine  = r'"' + PATH_JAVA + '"'
                    cmd_mustang_combine += r' -jar "' + PATH_MUSTANG + '"'
                    cmd_mustang_combine += r' --action combine'
                    cmd_mustang_combine += r' --source-xml "' + xmlFile + '"'
                    cmd_mustang_combine += r' --source "' + pdfFile + '"'
                    cmd_mustang_combine += r' --out "' + zugferd_pdf + '"'
                    cmd_mustang_combine += r' --format zf'
                    cmd_mustang_combine += r' --version 2'
                    cmd_mustang_combine += r' --profile T'
                    cmd_mustang_combine += r' --attachments ""'
                    if DEBUG is True: logger.debug("cmd_mustang_combine = {}".format(cmd_mustang_combine))
                    try:
                        proc = subprocess.Popen(cmd_mustang_combine, shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                        proc.wait()
                    except OSError as e:
                        raise OSError("{0}\nCommand failed: errno={1} {2}".format(' '.join(cmd), e.errno, e.strerror))
                    stdout, stderr = proc.communicate()
                    if stderr.decode('utf-8') != "":
                        logger.error("stderr: {}".format(stderr.decode('utf-8')))
                
                    if not os.path.exists(zugferd_pdf):
                        logger.error("ERROR: ZUGFeRD PDF Erzeugung fehlgeschlagen!")
                        return

```

then the validation:
```
                        validation_xml = os.path.join(basedir, stem + STEM_ZUGFERD_VALIDATION)
                        cmd_mustang_validate  = r'"' + PATH_JAVA + '"'
                        cmd_mustang_validate += r' -jar "' + PATH_MUSTANG + '"'
                        cmd_mustang_validate += r' --action validate'
                        cmd_mustang_validate += r' --source "' + zugferd_pdf + '" > "' + validation_xml + '"'
                        if DEBUG is True: logger.debug("cmd_mustang_validate = {}".format(cmd_mustang_validate))
                        try:
                            proc = subprocess.Popen(cmd_mustang_validate, shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                            proc.wait()
                        except OSError as e:
                            raise OSError("{0}\nCommand failed: errno={1} {2}".format(' '.join(cmd), e.errno, e.strerror))
```

The issue in validation xml output file, which is returned, is the following:

```DeviceCMYK shall only be used if a device independent DefaultCMYK colour space has been set or if a DeviceN-based DefaultCMYK colour space has been set when the DeviceCMYK colour space is used or the file has a PDF/A OutputIntent that contains a CMYK destination profile```

i have no explanation about that. Does it belong to monitor settings about the ICC color profile? I cannot change such settings because i am working on RDP remote sessions (on both machines; as explained on one it works, on the other it does not work).

Do i need some library or driver? Can i check sth. against the PDFs? by the way Mustang does not warn about something strange when creating ZUGFeRD PDF. It gives that warning in the validation, which is the second usage step

**Comment by vmario89** [comment]
might belong to https://github.com/ZUGFeRD/mustangproject/discussions/386

**Comment by vmario89** [comment]
might belong to veraPDF https://github-wiki-see.page/m/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Part-4-rules

**Comment by jstaerk** [comment]
The input validation is just a rough one and done with PDFbox, can you check your original PDF/A-3 file via VeraPDF? If that is invalid the output will also be invalid, but it would be an issue is the input was valid and the output invalid, i.e. if Mustang destroyed something.

Command line wise I [recommend ](https://www.mustangproject.org/commandline/) adding `-Xmx1G -Dfile.encoding=UTF-8` but the first parameter has so far only been needed in validation and the second in visualization.

**Comment by vmario89** [comment]
as it figures out it has nothing to do with the OS itself, but with the input pdf. i think i used two different PDF files which made the trouble. both came from the same softwae system, but from different clients. i think the original source PDF is not fully valid, even if it is configured to create PDF/A-3 output. i will play around with veraPDF to check what happens

thanks for the hint with the arguments for java. i already catched them my self. Are they documented anywhere? i found them at the examples at Mustang project homepage, but not with an explanation why to use them
