### ISSUE TITLE
No interface for required field CreditorReferenceID

### ISSUE THREAD

**Issue by robali** [ZUGFeRD/mustangproject#436]
I want to create a debit (Lastschriftverfahren) as a payment method. 
I do this by implementing and setting the interface IZUGFeRDTradeSettlementDebit. This allows me to set the IBAN and the Mandate. However, I didn’t find an interface to set the required field CreditorReferenceId (Gläubiger-ID). This should be an element directly below ApplicableHeaderTradeSettlement, but as far as I can tell, there are only interfaces for the attributes PaymentReference and InvoiceCurrentCode on this level, but not CreditorReferenceID. 

Am I overseeing the interface?

**Comment by jstaerk** [comment]
I'm not sure if it's already implemented, can you grep the source code?

**Comment by langfr** [comment]
```CreditorReferenceID``` does not yet appear anywhere in the java code, only within different resource files (xsd, xslt, sch) for validation an visualization.
As this value is a direct child of ```HeaderTradeSettlementType``` it should be part of class ```Invoice```, not part of ```IZUGFeRDTradeSettlementDebit```.
```
  <xs:complexType name="HeaderTradeSettlementType">
    <xs:sequence>
      <xs:element name="CreditorReferenceID" type="udt:IDType" minOccurs="0"/>
      <xs:element name="PaymentReference" type="udt:TextType" minOccurs="0"/>
      <xs:element name="TaxCurrencyCode" type="qdt:CurrencyCodeType" minOccurs="0"/>
      <xs:element name="InvoiceCurrencyCode" type="qdt:CurrencyCodeType"/>
      ...
```

**Comment by sebastianschmitz1510** [comment]
I think this issue relates to an other open issue: https://github.com/ZUGFeRD/mustangproject/issues/370

**Comment by robali** [comment]
right Sebastian, issue #370 adresses the exact same problem.

**Comment by robali** [comment]
I checked ... it's not implemented. Any chance it will be implemented in the next release :) ?

**Comment by langfr** [comment]
Created pull request #439 for this.

**Comment by robali** [comment]
awesome, thanks so much !!!
