### ISSUE TITLE
XRechnung: Embed attachments in xml

### ISSUE THREAD

**Issue by xgwslbe** [ZUGFeRD/mustangproject#437]
We currently working on including attachments into the pdf for a ZUGFeRD-PDF and into the xml for XRechnung.

For the pdf there is the function PDFAttachGenericFile, which works perfectly.

Is there a corresponding functionality for the XRechnung xml, that includes the attachment in the right xml tag etc.?

Thank you!

**Comment by sebastianschmitz1510** [comment]
Yes it works.
Here is an example: https://github.com/ZUGFeRD/mustangproject/blob/master/library/src/test/java/org/mustangproject/ZUGFeRD/XRTest.java#L98
