### ISSUE TITLE
Generated ZUGFeRD2.0  file contradicts Mustang validator

### ISSUE THREAD

**Issue by relhussein** [ZUGFeRD/mustangproject#449]
I'm using the Mustang framework to generate ZUGFeRD files for version 2 / profile EN16931.
The Mustang validator shows 3 issues: 

**1. Creditor Identifier**
Message: <notice type="27" location="/rsm:CrossIndustryInvoice" criterion="(($BT-89-path or $BT-91-path) and $BT-90-path) or $BG-19-not-existing">[BR-DE-30] Wenn "DIRECT DEBIT" BG-19 vorhanden ist, dann muss "Bank assigned creditor identifier" BT-90 übermittelt werden. [ID BR-DE-30] from /xslt/XR_30/XRechnung-CII-validation.xslt)</notice>  

Solution:
I think this will be solved in near future -> https://github.com/ZUGFeRD/mustangproject/issues/436

**2.Das Element "Specification identifier" (BT-24) soll syntaktisch der Kennung des Standards XRechnung entsprechen.**
Message: 
<notice type="27" location="/rsm:CrossIndustryInvoice/rsm:ExchangedDocumentContext[1]" criterion="ram:GuidelineSpecifiedDocumentContextParameter/ram:ID = $XR-CIUS-ID or ram:GuidelineSpecifiedDocumentContextParameter/ram:ID = $XR-EXTENSION-ID">[BR-DE-21] Das Element "Specification identifier" (BT-24) soll syntaktisch der Kennung des Standards XRechnung entsprechen. [ID BR-DE-21] from /xslt/XR_30/XRechnung-CII-validation.xslt)</notice>  

Solution; 
 I think this issue relates to this -> https://github.com/ZUGFeRD/mustangproject/issues/172
 Will there be a fix?

**3. Business process MUST be provided**
Message: notice type="27" location="/rsm:CrossIndustryInvoice/rsm:ExchangedDocumentContext[1]" criterion="ram:BusinessProcessSpecifiedDocumentContextParameter/ram:ID">Business process MUST be provided. [ID PEPPOL-EN16931-R001] from /xslt/XR_30/XRechnung-CII-validation.xslt)</notice>  

To solve this, I think 
```
         <ram:GuidelineSpecifiedDocumentContextParameter>
		      <ram:ID>urn:cen.eu:en16931:2017</ram:ID>
	        </ram:GuidelineSpecifiedDocumentContextParameter>
``` 

	should be 
```
<ram:BusinessProcessSpecifiedDocumentContextParameter>
		<ram:ID>urn:fdc:peppol.eu:2017:poacc:billing:01:1.0</ram:ID>
	</ram:BusinessProcessSpecifiedDocumentContextParameter>
```

**Comment by jstaerk** [comment]
hi, could you please attach the whole sample (and maybe even the source?) so that to make the issues reproducible?

**Comment by relhussein** [comment]
Hi jstaerk, so you need the whole xml-file if possible?

**Comment by relhussein** [comment]
Hi jstaerk, here is the output of the validator:

```xslt
<?xml version="1.0" encoding="UTF-8"?>

<validation filename="ZF_generated.pdf" datetime="2024-08-21 09:34:22">
  <pdf>ValidationResult [flavour=3u, totalAssertions=11286, assertions=[], isCompliant=true]
    <info>
      <signature>Mustang</signature>
      <duration unit="ms">1539</duration>
    </info>
    <summary status="valid"/>
  </pdf>  
  <xml>
    <info>
      <version>2</version>
      <profile>urn:cen.eu:en16931:2017</profile>
      <validator version="2.12.0"/>
      <rules>
        <fired>16</fired>
        <failed>3</failed>
      </rules>
      <duration unit="ms">3180</duration>
    </info>
    <messages>
      <notice type="27" location="/rsm:CrossIndustryInvoice/rsm:ExchangedDocumentContext[1]" criterion="ram:BusinessProcessSpecifiedDocumentContextParameter/ram:ID">Business process MUST be provided. [ID PEPPOL-EN16931-R001] from /xslt/XR_30/XRechnung-CII-validation.xslt)</notice>  
      <notice type="27" location="/rsm:CrossIndustryInvoice" criterion="(($BT-89-path or $BT-91-path) and $BT-90-path) or $BG-19-not-existing">[BR-DE-30] Wenn "DIRECT DEBIT" BG-19 vorhanden ist, dann muss "Bank assigned creditor identifier" BT-90 übermittelt werden. [ID BR-DE-30] from /xslt/XR_30/XRechnung-CII-validation.xslt)</notice>  
      <notice type="27" location="/rsm:CrossIndustryInvoice/rsm:ExchangedDocumentContext[1]" criterion="ram:GuidelineSpecifiedDocumentContextParameter/ram:ID = $XR-CIUS-ID or ram:GuidelineSpecifiedDocumentContextParameter/ram:ID = $XR-EXTENSION-ID">[BR-DE-21] Das Element "Specification identifier" (BT-24) soll syntaktisch der Kennung des Standards XRechnung entsprechen. [ID BR-DE-21] from /xslt/XR_30/XRechnung-CII-validation.xslt)</notice> 
    </messages>
    <summary status="valid"/>
  </xml>
  <messages></messages>
  <summary status="valid"/>
</validation>

``` 

And please find attached the pdf that generates these errors. Hope it helps & thank you. 

[Uploading ZF.pdf…]()

**Comment by jstaerk** [comment]
Hello, 

it seems as what you describe are mere notices, if you run with --no-notices they will disappear. The idea was that if you feed a EN16931 the software checks if it's by any chance also a valid XRechnung and if not, gives the user a hint a lá "and if you also specify XYZ" you would also get a XRechnung. 

kind regards
JOchen
