### ISSUE TITLE
invoices have wrong namespaces

### ISSUE THREAD

**Issue by jstaerk** [ZUGFeRD/mustangproject#45]
e.g. `<ns3:CrossIndustryDocument` instead of `<ram:CrossIndustryDocument `

**Comment by jstaerk** [comment]
I added an according test added on the weekend but I didn't finalize the correction, it currently fails

**Comment by jstaerk** [comment]
Besides, the namespace prefixes are fixed by the standard which means that the switch to JAXB for ZF1 export is probably incomplete until I finished some custom namespace prefix mapper -- does anybody know why they apparently had to be standardized? Is that schematron related? I personally already consider it a design flaw that the namespaces are static, not to speak of the prefixes.

**Comment by jstaerk** [comment]
@yankee42 can you help? I tried with NamespacePrefixMapper both on `com.sun.xml.bind.namespacePrefixMapper` and `com.sun.xml.internal.bind.marshaller.NamespacePrefixMapper` transformSchemas (http://www.mojohaus.org/jaxb2-maven-plugin/Documentation/v2.2/example_schemagen_postprocessing.html) but to no avail. In the worst case I'd have to go for a string replace...

**Comment by yankee42** [comment]
All that should be needed is:
```java
marshaller.setProperty("com.sun.xml.bind.namespacePrefixMapper", new NamespacePrefixMapper() {
	@Override
	public String getPreferredPrefix(final String namespaceUri, final String suggestion, final boolean requirePrefix) {
		return somethingUsefulBasedOnParameters;
	}
});
```
Pkease push your failing test somewhere if that does not help.
