### ISSUE TITLE
Provide a way to set uriUniversalCommunicationId on the TradeParty using JSON deserialization

### ISSUE THREAD

**Issue by phermsdorf** [ZUGFeRD/mustangproject#456]
Hi,

to create a valid xRechnung we need to be able to set the EMail Adress of a TradeParty. A setter would maybe look like this:

```
public void setUniversalCommunicationId(final String email) {
	uriUniversalCommunicationId = new SchemedID("EM", email);
}
```
Since we want to create the Invoice and TradeParty Objects by deserializing from JSON we need a way to set uriUniversalCommunicationId like the other values in the DeSerializationTest.java.

If you guide me a bit, i could also try to provide a pull request.
Thank you!

Bye Peter

**Comment by jstaerk** [comment]
hi, did this work?

**Comment by phermsdorf** [comment]
Yes, i tried to document the usage by adjusting the test case in #460 . You need to use the `setEmail` method which internally creates the correct SchemeID and email address.
