### ISSUE TITLE
Multiple ClassNotFoundExceptions

### ISSUE THREAD

**Issue by uwemock** [ZUGFeRD/mustangproject#474]
When I use Mustang 2.12.0 or 2.13.0, I receive multiple ClassNotFoundExceptions, e.g.

org.dom4j.io.XMLWriter
`at org.mustangproject.Item.<init>(Item.java:75)
	at org.mustangproject.ZUGFeRD.ZUGFeRDInvoiceImporter.extractInto(ZUGFeRDInvoiceImporter.java:344)
	at org.mustangproject.ZUGFeRD.ZUGFeRDInvoiceImporter.extractInvoice(ZUGFeRDInvoiceImporter.java:446)`

org.apache.pdfbox.Loader
`at org.mustangproject.ZUGFeRD.ZUGFeRDImporter.extractLowLevel(ZUGFeRDImporter.java:124)
	at org.mustangproject.ZUGFeRD.ZUGFeRDImporter.<init>(ZUGFeRDImporter.java:101)`

Are there any missing dependencies?

**Comment by jstaerk** [comment]
Hi,
Did you switch to the shaded version #422 already?
kind regards
Jochen

**Comment by uwemock** [comment]
No. I wasn't aware of this, well, weird workaround.

**Comment by J-N-K** [comment]
> No. I wasn't aware of this, well, weird workaround.

I agree. In general I would suggest to add the correct dependencies to you project's POM (if using maven, not sure how to do that in gradle). For the first missing class you need

```
        <dependency>
            <groupId>org.dom4j</groupId>
            <artifactId>dom4j</artifactId>
            <version>2.1.4</version>
        </dependency>
```

The second class is from PDFBox. Did you switch to PDFBox 3? If not, upgrade your dependencies, we use

```
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>pdfbox</artifactId>
            <version>3.0.3</version>
        </dependency>
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>preflight</artifactId>
            <version>3.0.3</version>
        </dependency>
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>xmpbox</artifactId>
            <version>3.0.3</version>
        </dependency>
```

In case your application is Spring (or similar) check that no other component draws in PDFBox 2.

**Comment by uwemock** [comment]
Thanks for the suggestion. I chose the shaded version for now, and it works well. Maybe I will change this later.
In general, the client should not be responsible for the transitive dependencies.
