### ISSUE TITLE
Quantity Decimal Places Limitation Conflicts with XRechnung Compliance (Needs Immediate Fix)

### ISSUE THREAD

**Issue by fktrdui** [ZUGFeRD/mustangproject#494]
According to the XRechnung specification, as highlighted in the attached screenshot (section 8.8 "Quantity"), the quantity values should not have a limitation on decimal places. The specification explicitly mentions that the quantity field should allow a floating-point number without limitation on decimal places ("ohne Limitierung der Nachkommastellen").
![quantityFormat](https://github.com/user-attachments/assets/f9591d2f-2b4b-45ac-8c57-2b0e02296013)

However, the Mustang project appears to limit the number of decimal places for quantities in certain methods. 
Specifically, in the ZUGFeRD2PullProvider class, the quantityFormat method restricts quantities to 4 decimal places:
```
protected String quantityFormat(BigDecimal value) {
    return XMLTools.nDigitFormat(value, 4);
}
```
This method is called by:
```
+ "<ram:BasisQuantity unitCode=\"" + XMLTools.encodeXML(currentItem.getProduct().getUnit())
+ "\">" + quantityFormat(currentItem.getBasisQuantity()) + "</ram:BasisQuantity>"

```
Additionally, in the IZUGFeRDExportableItem interface, the getBasisQuantity() method also uses BigDecimal.ONE.setScale(4), which imposes a restriction of 4 decimal places for the quantity.
```
default BigDecimal getBasisQuantity() {
    return BigDecimal.ONE.setScale(4);
}
```

**Request for Immediate Action**
This issue requires urgent attention as it directly impacts XRechnung compliance. Non-compliant e-invoices could lead to legal and financial risks, such as invoice rejections.

**Proposed Fix**: 
Modify the following methods to allow arbitrary precision for quantity values:
quantityFormat in the ZUGFeRD2PullProvider class.
getBasisQuantity in the IZUGFeRDExportableItem interface.

**Comment by fktrdui** [comment]
Thank you for your immediate update.
Due to changes there are some test issues in the project:

Failed tests:   testDXExport(org.mustangproject.ZUGFeRD.DXTest): expected:<400.0000> but was:<400.000000000000000000>
  testOXEdgeExport(org.mustangproject.ZUGFeRD.OXTest): expected:<1.0000> but was:<1.000000000000000000>
  testOXExport(org.mustangproject.ZUGFeRD.OXTest): expected:<400.0000> but was:<400.000000000000000000>
  testExport(org.mustangproject.ZUGFeRD.ZF2Test): expected:<1.0000[00000000000000]> but was:<1.0000[]>
  testInvoiceImport(org.mustangproject.ZUGFeRD.ZF2ZInvoiceImporterTest): expected:<400.0000[]> but was:<400.0000[00000000000000]>

**Comment by langfr** [comment]
PR #497 created to fix these issues.

**Comment by jstaerk** [comment]
@fktrdui can you provide one or two tests?

**Comment by fktrdui** [comment]
@jstaerk I would be happy to modify the previous tests

**Comment by fktrdui** [comment]
Updated **testOXEdgeExport** Test Case:
```
public void testOXEdgeExport() {
    // the writing part
    try (InputStream SOURCE_PDF = this.getClass()
            .getResourceAsStream("/MustangGnuaccountingBeispielRE-20170509_505blanko.pdf");

         OXExporterFromA1 oe = new OXExporterFromA1().setProducer("My Application")
                 .setCreator(System.getProperty("user.name")).setZUGFeRDVersion(1).ignorePDFAErrors()
                 .load(SOURCE_PDF)) {
        TradeParty rec = new TradeParty("Franz Müller", "teststr.12", "55232", "Entenhausen", "DE");
        Invoice i = new Invoice().setDueDate(new Date()).setIssueDate(new Date()).setDeliveryDate(new Date())
                .setSender(new TradeParty("Test company", "teststr", "55232", "teststadt", "DE").addTaxID("DE4711")
                        .addVATID("DE0815")
                        .setContact(new Contact("Hans Test", "+49123456789", "test@example.org"))
                        .addBankDetails(new BankDetails("DE12500105170648489890", "COBADEFXXX")))
                .setRecipient(rec)
                .setReferenceNumber("991-01484-64") // leitweg-id
                .setNumber("123")
                .addItem(new org.mustangproject.Item(new org.mustangproject.Product("Testprodukt", "", "C62", BigDecimal.ZERO),
                        /*price*/ new BigDecimal("1.0"), /*qty*/ new BigDecimal("1.0")))
                .addItem(new org.mustangproject.Item(new org.mustangproject.Product("Testprodukt", "", "C62", BigDecimal.ZERO),
                        /*price*/ new BigDecimal("1.0"), /*qty*/ new BigDecimal("1.0")));

        oe.setTransaction(i);
        oe.export(TARGET_PDF_EDGE);
    } catch (IOException e) {
        fail("IOException should not be raised in testEdgeExport");
    }

    // now check the contents (like MustangReaderTest)
    ZUGFeRDImporter zi = new ZUGFeRDImporter(TARGET_PDF_EDGE);

    assertTrue(zi.getUTF8().contains("<ram:TypeCode>220</ram:TypeCode>"));
    assertTrue(zi.getUTF8().contains("<ram:ShipToTradeParty>"));
    assertTrue(zi.getUTF8().contains("EUR"));

    // Now also check the "invoice"Importer
    assertEquals("2.00", zi.getAmount());
    assertEquals(zi.getHolder(), "Test company");

    ZUGFeRDInvoiceImporter zii = new ZUGFeRDInvoiceImporter(TARGET_PDF_EDGE);
    try {
        Invoice i = zii.extractInvoice();

        // Updated assertion: The expected value no longer includes trailing zeros
        assertEquals(new BigDecimal("1"), i.getZFItems()[1].getQuantity());

        /*
         * Getting the Quantity is more difficult than usual because in OrderX it's
         * called requestedQuantity, not BilledQuantity
         */
    } catch (XPathExpressionException e) {
        fail("XPathExpressionException should not be raised in testEdgeExport");
    } catch (ParseException e) {
        fail("ParseException should not be raised in testEdgeExport");
        /* a parseException would also be fired if the calculated grand total does not
         * match the read grand total */
    }
}

```

**Comment by fktrdui** [comment]
Modified Test Cases:

1. **org.mustangproject.ZUGFeRD.DXTest: testDXExport**
Line 301:
`assertEquals(new BigDecimal("400"), i.getZFItems()[1].getQuantity());
`
2. **org.mustangproject.ZUGFeRD.OXTest: testOXExport**
Line 300:
`assertEquals(new BigDecimal("400"), i.getZFItems()[1].getQuantity());
`
3.  **org.mustangproject.ZUGFeRD.OXTest: testOXEdgeExport**
Line 354:
`assertEquals(new BigDecimal("1"), i.getZFItems()[1].getQuantity());
`
4. **org.mustangproject.ZUGFeRD.ZF2Test: testExport**
Line 236:
`assertEquals(li.get(0).getQuantity().toString(), "1");`

5. **org.mustangproject.ZUGFeRD.ZF2ZInvoiceImporterTest: testInvoiceImport**
Line 60-63:
```
assertEquals("400", invoice.getZFItems()[1].getQuantity().toString());
assertEquals("AB321", invoice.getReferenceNumber());
assertEquals("160", invoice.getZFItems()[0].getPrice().toString());
```
