### ISSUE TITLE
Text overlay in generated PDF for field "Spezifikationskennung"

### ISSUE THREAD

**Issue by zeratools** [ZUGFeRD/mustangproject#499]
Hello,

I generate a PDF from this UBL XRechnung XML file https://github.com/itplr-kosit/xrechnung-testsuite/blob/master/src/test/business-cases/standard/01.01a-INVOICE_ubl.xml
It's working fine except there is a text overlay at the end on the "Spezifikationskennung" field
See screen capture and full XML generated bellow.

This test is based on master branch code.

![image](https://github.com/user-attachments/assets/de622337-4750-485a-aead-b7f22fe4880f)
[01.01a-INVOICE_ubl.xml.pdf](https://github.com/user-attachments/files/17229572/01.01a-INVOICE_ubl.xml.pdf)

Best regards

**Comment by zeratools** [comment]
After some research in the code base, this overlay is caused by the presence of both CustomizationID and ProfileID in the XML:

```xml
    <cbc:CustomizationID>urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0</cbc:CustomizationID>
    <cbc:ProfileID>urn:fdc:peppol.eu:2017:poacc:billing:01:1.0</cbc:ProfileID>
```

This section layout in PDF is 2 column but the URN used as ID are too long for that display.
I will provide a pull request to switch this section on single column layout.

**Comment by jstaerk** [comment]
thank you, merged, I hope it is non destructive :-)
