### ISSUE TITLE
Rework: Fix non terminating decimal expansion error in Linecalculator

### ISSUE THREAD

**Issue by rchilumukoti** [ZUGFeRD/mustangproject#501]
Hi Mustang team,

Unfortunately Issue  #491 "Fix non terminating decimal expansion error in Linecalculator" is not fixed properly. 

RoundingMode.HALF_UP parameter was supposed to be added at line 43 divide function instead of divide function at line 40. Hence the testcase is testNonTerminatingDecimalExpansion in CalculationTest still failing. Can you please fix it. 

Thank you.

Regards
Rajani

**Comment by jstaerk** [comment]
hi,
should be fixed. Apologies.

For further issues please feel free to fork, commit, push and pull-request if you like.

kind regards
Jochen

**Comment by jstaerk** [comment]
Actually, @rchilumukoti , I believe we might need a rework of the rework, zf2EdgeTest.testEdgeExport will fail if rounded like this, there we have a 160€ per 100 units and 1 unit is assigned, should be 1.6€, with your rounding its 2 :-(

**Comment by jstaerk** [comment]
it does seem to work for both, though, if you specify a scale, like
'itemTotalNetAmount = currentItem.getQuantity().multiply(getPrice()).divide(currentItem.getBasisQuantity(), 18, RoundingMode.HALF_UP)' but then the question is: is there an answer how high the scale should be? 18 is like from Chapter 3.2.3 of https://www.w3.org/TR/xmlschema-2/
