### ISSUE TITLE
Link to doc in README is wrong

### ISSUE THREAD

**Issue by mksplg** [ZUGFeRD/mustangproject#51]
The link to the documenation in the `README.md` section [Running](https://github.com/ZUGFeRD/mustangproject/blob/614af5cb5fa317f2213df15035e705bb649ac99a/README.md#running) should point to `https://github.com/ZUGFeRD/mustangproject/blob/master/doc/ZugferdDev.en.pdf`.

Also there is a bracket too much at the end of the line.

I also think the text should be `More information in the mustang documentation.` as `information` [has not plural](https://en.oxforddictionaries.com/definition/information).

**Comment by jstaerk** [comment]
done, thanks
