### ISSUE TITLE
Quba Viewer 1.4.0 Printing doesn't work

### ISSUE THREAD

**Issue by stefan1241** [ZUGFeRD/mustangproject#515]
I installed Quba-Viewer 1.4.0 on a Windows 10 machine.

Printing on a real printer or a PDF-Printer doesn't work. Only the first tab (Overview) is printed but not
completely. All the other tabs (position, information, attachments ...) are not printed at all.

Neither the PDF-View nor the XML-View works.

Best regards 
Stefan

**Comment by stefan1241** [comment]
Sorry, wrong issue tracker

**Comment by jstaerk** [comment]
+already solved in dev https://github.com/ZUGFeRD/quba-viewer/issues/54 :-)
