### ISSUE TITLE
Verapdf claims PDF-A/3s created witth visualize are invalid 

### ISSUE THREAD

**Issue by jstaerk** [ZUGFeRD/mustangproject#523]
Specification: ISO 19005-3:2012, Clause: 6.6.2.3.1, Test number:2 

Could be an issue in, from, or related to Apache fop, upstreamed as https://issues.apache.org/jira/browse/FOP-3214

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by jstaerk** [comment]
+upstreamed at https://github.com/itplr-kosit/xrechnung-visualization/pull/16
