### ISSUE TITLE
Extra whitespace causing format exceptions

### ISSUE THREAD

**Issue by lolletsoc** [ZUGFeRD/mustangproject#525]
Hey everyone,

We have a case where whitespace is causing `BigDecimal` conversion errors - see [here](https://github.com/ZUGFeRD/mustangproject/blob/52ddff4f7ac0bf9ee7f63854499c73ee503de767/library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDInvoiceImporter.java#L328)

Obviously, the creator of the e-invoice shouldn't be adding extra whitespace around values, but alas, here we are. Other tools seem to handle this gracefully. I would like to submit a PR with whitespace trimmed but figured I'd check in here first.

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
