### ISSUE TITLE
Dependency conflict with org.apache.pdfbox, fontbox

### ISSUE THREAD

**Issue by mksplg** [ZUGFeRD/mustangproject#53]
Since this package uses the shade plugin, classes from org.apache.pdfbox and org.apache.fontbox are copied into the jar in the package phase. This is great for creating a standalone executable jar to execute from the commandline as it includes everything needed in the specific version. 

When using the package as a library in a project that also depends on pdfbox or fontbox, the copied classes may conflict with the versions defined as dependencies of the project. For example the version specified in mustangproject is `2.0.5` but the project *using* mustangproject needs `2.0.8`, leading to conflicts.

In my case, version `2.0.8` of pdfbox fixes an issue with embedding subsets of fonts in PDF/A files. Normally when specifying a different version in the project using mustangproject I would add pdfbox to the dependencies and maven would load my version instead of the version mustangproject depends on. Unfortunately this is not possible since mustangproject already provides version `2.0.5` copied to the jar.

**Comment by jstaerk** [comment]
I don't find it in the maven artifacts, in case you would not use maven, shade would build a 

- mustang-1.5.1.jar (5,4MiB)

 with dependencies - could you potentially make use of the 

- original-mustang-1.5.1.jar (137 KiB)

 it will simultaneously build without the dependencies?

**Comment by mksplg** [comment]
The jar [mustang-1.5.1.jar](https://github.com/ZUGFeRD/mustangproject/blob/mvn-repo/org/mustangproject/ZUGFeRD/mustang/1.5.1/mustang-1.5.1.jar) deployed in the maven repository directly contains the all classes of the dependencies, i.e. there is a folder `org/apache/pdfbox`. The [pom.xml](https://github.com/ZUGFeRD/mustangproject/blob/mvn-repo/org/mustangproject/ZUGFeRD/mustang/1.5.1/mustang-1.5.1.pom) has all dependencies stripped meaning maven does not know about the dependencies:
```
+--- [...]
+--- org.mustangproject.ZUGFeRD:mustang:1.5.1
+--- [...]
```

This means there is no way to use a different version of the dependencies as they are already included in mustang-1.5.1.jar. Preferably the dependencies could be kept in the pom.xml, maybe even without jargs.
```
+--- [...]
+--- org.mustangproject.ZUGFeRD:mustang:1.5.5
|    +--- com.sun.xml.bind:jaxb-impl:2.2.11
|    +--- com.sun.xml.bind:jaxb-core:2.2.11
|    +--- org.glassfish.jaxb:jaxb-runtime:2.2.11 (*)
|    +--- org.apache.pdfbox:preflight:2.0.5
|    |    +--- org.apache.pdfbox:pdfbox:2.0.5 -> 2.0.8 (*)
|    |    \--- org.apache.pdfbox:xmpbox:2.0.5 -> 2.0.8 (*)
|    +--- org.apache.pdfbox:pdfbox:2.0.5 -> 2.0.8 (*)
|    \--- com.sanityinc:jargs:2.0-SNAPSHOT
+--- [...]
```
This way the user can override the dependency version, e.g. ` org.apache.pdfbox:pdfbox:2.0.5 -> 2.0.8 (*)`.

I think when deploying the jar to a repository it should not contain dependencies so the user of the package has the possibility to overwrite the needed version.

I'm not sure what the best method for this case is, you could:
* Only deploy the `original-mustang-1.5.1.jar`, maybe use profiles to allow creating different jars (executable and library)
* Create separate projects, one *library* project, one `commandline` project
* Use shade pluing [class relocation](https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html) to rename the classes.

**Comment by joehni** [comment]
We use in a large project all kind of PDF and XML processing and we tried to add mustang, but these bundled classes generate all kind of errors and unwanted effects. It is fine for an application to bundle the dependencies in a single jar, but for a library that should be used in a bigger concert it is an absolute no-go. Especially for a Maven-based project, where all required dependencies are automatically managed, it is essential to have a normal library and POM with declared deps.

Please consider Markus' advice. A separate commandline artifact that contains all stuff is fine, but for a proper projects with dependency management we need the base library. In the current form it is not usable.

**Comment by seizmo** [comment]
This is also quite a showstopper for us. Artifacts pushed to the maven repo should never contain the dependencies. The shade plugin is fine for standalone jars (which should be named as such, mustang-standalone.jar or smth.), but not for libraries.

**Comment by dovogt** [comment]
We also have the problem that we need the Mustang library without the dependencies.
Is it possible to provide the library without dependencies with pom file. (no fatjar)

**Comment by jstaerk** [comment]
the library without dependencies is available via https://www.mustangproject.org/deploy/original-mustang-1.7.8.jar and the whole thing is now also on maven central (in case anybody needs it with gradle)
