### ISSUE TITLE
Are codes (eg. VatExemptionReasonCode) case sensititive?

### ISSUE THREAD

**Issue by hvbtup** [ZUGFeRD/mustangproject#549]
I updated from Mustang 2.11 to 2.14.
Now the validator complains about `vatex-eu-ae`.
I had to change the value to `VATEX-EU-AE`.

Looking at the official code list at https://www.xrepository.de/details/urn:xoev-de:kosit:codeliste:vatex_1,
the codes are shown in lowercase there.
But the validator expects uppercase values.

I could not find any official statement anywhere if the codes are case sensitive or not.

If they are case-sensitive, then the documentation of EN16931 and XRechnung should clarify this.
If not, then the look-up code should in the validator should be case-insensitive.

**Comment by jstaerk** [comment]
the schematron files contain the uppercase version only feel free to ask them to clarify e.g. at https://github.com/ConnectingEurope/eInvoicing-EN16931/ and/or https://github.com/itplr-kosit/validator-configuration-xrechnung
