### ISSUE TITLE
Fehlendes DueDate bei der Erzeugung von CreditNotes

### ISSUE THREAD

**Issue by RaukampMika** [ZUGFeRD/mustangproject#550]
Moin,

ich versuche gerade eine CreditNote zu erzeugen, im Validator bekomme ich aber einen Fehler der ähnlich zu #307 ist.

```
BR-CO-25]-In case the Amount due for payment (BT-115) is positive, either the Payment due date (BT-9) or the Payment terms (BT-20) shall be present. [ID FX-SCH-A-000155] from /xslt/ZF_230/FACTUR-X_EXTENDED.xslt)
/*:CrossIndustryInvoice[namespace-uri()='urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100'][1]
```

Das DueDate habe ich versucht zu setzen, jedoch wird es wieder entfernt bei einer CreditNote.
So habe ich es auch in der Klasse "ZUGFeRD2PullProvider" gefunden

```
if (trans.getDocumentCode() == "384" || trans.getDocumentCode() == "381") {
            hasDueDate = false;
        }
```

Viele Grüße 
Mika

**Comment by JohnHuynh** [comment]
Ich habe genau dasselbe Problem. 

Vielleicht könnte man im Zuge des Issues auch die Konfigurierbarkeit der `paymentTermsDescription` (BT-20) verbessern, weil der Text der `paymentTermsDescription` momentan hartkodiert ist: 

```
if (trans.getDueDate() != null) {
    paymentTermsDescription = "Please remit until " + germanDateFormat.format(trans.getDueDate());
}
```

**Comment by langfr** [comment]
Zu der letzten Anmerkung mit dem festen Text:
dieser hart kodierte Text wird nur benutzt, wenn kein eigener Text angegeben wurde und auch nur wenn's keine Korrekturrechnung oder Gutschrift ist.
Siehe
https://github.com/ZUGFeRD/mustangproject/blob/d8ba8347054396dfc7871a09c76994d18b5a93ec/library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java#L355-L359

Für die Angabe eines eigenen Textes gibt es ```org.mustangproject.Invoice.setPaymentTermDescription(String)```

**Comment by JohnHuynh** [comment]
> Zu der letzten Anmerkung mit dem festen Text: dieser hart kodierte Text wird nur benutzt, wenn kein eigener Text angegeben wurde und auch nur wenn's keine Korrekturrechnung oder Gutschrift ist. Siehe
> 
> https://github.com/ZUGFeRD/mustangproject/blob/d8ba8347054396dfc7871a09c76994d18b5a93ec/library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRD2PullProvider.java#L355-L359
> 
> Für die Angabe eines eigenen Textes gibt es `org.mustangproject.Invoice.setPaymentTermDescription(String)`

Super vielen Dank! Da war ich wohl zu voreilig...

Damit lässt sich das Problem dann auch umgehen, was hier beschrieben wurde: `either the Payment due date (BT-9) or the Payment terms (BT-20) shall be present`.

Wir machen also Gebrauch von `BT-20` statt `BT-9`.
