### ISSUE TITLE
IncludedNotes werden nicht ausgelesen

### ISSUE THREAD

**Issue by marco-lennartz** [ZUGFeRD/mustangproject#551]
Hallo, 

beim Auslesen der Invoice aus der Beispieldatei 
[EN16931_Einfach.pdf](https://github.com/user-attachments/files/17673005/EN16931_Einfach.pdf)
von Zugferd 2.3 werden die beiden Elemente
```xml
    <ram:IncludedNote>
      <ram:Content>Rechnung gemäß Bestellung vom 01.11.2024.</ram:Content>
    </ram:IncludedNote>
    <ram:IncludedNote>
      <ram:Content>Lieferant GmbH				
Lieferantenstraße 20				
80333 München				
Deutschland				
Geschäftsführer: Hans Muster
Handelsregisternummer: H A 123
      </ram:Content>
      <ram:SubjectCode>REG</ram:SubjectCode>
    </ram:IncludedNote>
```
nicht ausgelesen.

So weit ich das erkennen kann, werden [hier](https://github.com/ZUGFeRD/mustangproject/blob/d8ba8347054396dfc7871a09c76994d18b5a93ec/library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDInvoiceImporter.java#L335-L356) nur die Elemente ID, TypeCode und IssueDateTime ausgelesen.

Wenn ich die IncludedNotes mittels [dieser Methode](https://github.com/ZUGFeRD/mustangproject/blob/d8ba8347054396dfc7871a09c76994d18b5a93ec/library/src/main/java/org/mustangproject/ZUGFeRD/ZUGFeRDImporter.java#L226) auslese erhalte ich leider nur die erste Notiz.

**Comment by InnuceEAN** [comment]
Für die IncludedNote in den Positionen scheint es auch nichts zu geben:

```xml
<ram:AssociatedDocumentLineDocument>
<ram:LineID>1</ram:LineID>
<ram:IncludedNote>
        <ram:Content>FB-LE 9999</ram:Content>
        <ram:SubjectCode>ABZ</ram:SubjectCode>
</ram:IncludedNote>
</ram:AssociatedDocumentLineDocument>
```

Ich habe es gerade hinbekommen über einen "Stunt" wie
```java
zii.wExtractString(String.format("//*[local-name() = 'AssociatedDocumentLineDocument'][%d]//*[local-name() = 'IncludedNote'][*[local-name() = 'SubjectCode'and text() = 'ABZ']]//*[local-name() = 'Content']", row+1));
```
imho wäre es praktisch direkt an die Rohdaten ranzukommen, z.B. per item.getRawXML() oder zii.wExtractString(item, "/x-path.."), damit sich solche Sachen einfach parsen lassen.

**Comment by marco-lennartz** [comment]
Für die IncludedNotes auf Rechnungsebene habe ich einen PR eingestellt. Siehe #554

**Comment by jstaerk** [comment]
sorry haben wir mittlerweile auch so gefixed
