### ISSUE TITLE
Duplicate Method setContent in IncludedNote.java

### ISSUE THREAD

**Issue by ThomasChr** [ZUGFeRD/mustangproject#598]
This can't be right?
![image](https://github.com/user-attachments/assets/20106c0b-48f4-4d32-8c39-3f7da85ad5ab)

Link to first setContent-Method: https://github.com/ZUGFeRD/mustangproject/blob/7c9f17218ae097541c1dfc65d7ffed322cd8510b/library/src/main/java/org/mustangproject/IncludedNote.java#L75
Link to seconds setContent-Method: https://github.com/ZUGFeRD/mustangproject/blob/7c9f17218ae097541c1dfc65d7ffed322cd8510b/library/src/main/java/org/mustangproject/IncludedNote.java#L90

**Comment by langfr** [comment]
Setters were already added with the previous commit a7db7acc1df1a4bc5566e8137bb98de2facfb7ae.
One setter got replaced, one duplicated.

In general I would really appreciate, that current master does compile and run tests successfully after every commit.

**Comment by jstaerk** [comment]
>In general I would really appreciate, that current master does compile and run tests successfully after every commit.
No
