### ISSUE TITLE
Nullpointer by extracting a ZUGFeRD-Document

### ISSUE THREAD

**Issue by vlimi** [ZUGFeRD/mustangproject#60]
The extraction of a ZUGFeRD-Document bring a Nullpointer-Error
Error at line 86 form ZUGFeRDImporter Class.

java.lang.NullPointerException: null
	at org.mustangproject.ZUGFeRD.ZUGFeRDImporter.extractLowLevel(ZUGFeRDImporter.java:86) ~[mustang-1.5.1.jar:?]
	at org.mustangproject.ZUGFeRD.ZUGFeRDImporter.extract(ZUGFeRDImporter.java:63) ~[mustang-1.5.1.jar:?]
	at de.css.global.zugferd.ZugFerdTools.initialisiereZUGFeRDImporter(ZugFerdTools.java:134) ~[classes/:?]
	at de.css.global.zugferd.ZugFerdTools.<init>(ZugFerdTools.java:95) ~[classes/:?]
	at de.css.fibu.beleg.RechnungImporter.erzeugeFibuBelege(RechnungImporter.java:106) [classes/:?]
	at de.css.fibu.beleg.FibuBelegRechnungLogic$1.doWork(FibuBelegRechnungLogic.java:213) [classes/:?]
	at de.integris.kit.ctl.ControlableThread.run(ControlableThread.java:426) [ikit.jar:?]
2018-07-13T09:31:54,249 [e-Rechnungsimport] ERROR RechnungImporter ~ Catching

**Comment by jstaerk** [comment]
Hi, 
can you please attach or send me an according file so that I can try to reproduce the error?
Thanks and kind regards
Jochen

**Comment by jstaerk** [comment]
@vlimi ?

**Comment by vlimi** [comment]
I have allready attached the File at the beginning of the first message.
[RE-5443520-20180712-5363140.pdf](https://github.com/ZUGFeRD/mustangproject/files/2196586/RE-5443520-20180712-5363140.pdf)

Thank

**Comment by jstaerk** [comment]
Very interesting, the file is valid but PDFBox seems to return null for the filename keyset

**Comment by vlimi** [comment]
Oh! But ist there any way to fix the Nullpointer and  extracting the needed informations?

**Comment by schube** [comment]
I have the same problem. Using the example PDF from https://www.pdflib.com/fileadmin/pdflib/pcos-cookbook/pdf/zugferd_invoice.pdf 
and "MustangGnuaccountingBeispielRE-20170509_505blanko.pdf
http://www.mustangproject.org/files/MustangGnuaccountingBeispielRE-20170509_505blanko.pdf" from your own website.

`Exception in thread "main" java.lang.NullPointerException
	at org.mustangproject.ZUGFeRD.ZUGFeRDImporter.extractLowLevel(ZUGFeRDImporter.java:110)
	at org.mustangproject.ZUGFeRD.ZUGFeRDImporter.extract(ZUGFeRDImporter.java:85)
	at org.mustangproject.toecount.Toecount.main(Toecount.java:369)
`

**Comment by jstaerk** [comment]
Thanks, gentlemen that was an important fix because it e.g. also affects https://github.com/ZUGFeRD/ZUV/ . A binary of the snapshot is available on http://mustangproject.org/deploy/mustang-1.5.3-SNAPSHOT.jar until the new version goes live.  @schube I added the sample to https://github.com/ZUGFeRD/corpus/ as it's apparently public, @vlimi can I add your invoice as well or is it confidential?

**Comment by vlimi** [comment]
Thank you very mucht for the correction. It works now and the extraction goes on. 
Unfortunatly, the Invoice that I added to this Issue ist confidential. Please don´t publish it.

**Comment by schube** [comment]
@jstaerk Thank you, works!

**Comment by jstaerk** [comment]
I had submitted this as part of my public preview feedback vis a vis Stefan Engel Flechsig.
Alexis De Lattre today found out that this seems also to be the way ghostscript attaches files to PDF/A-3 and he looks into a little ghostscript patch

**Comment by jstaerk** [comment]
Today I received the authoritative answer from Dr. Wild in german: they are both allowed, the example was just an example.

```

Beide Schreibweisen (Flat Array als auch Names Tree) sind für die Inhalte des Objekts EmbeddedFiles zulässig. Dass kommt daher, dass beide Schreibweisen eigentlich Names Trees sind, nur ist die ersteSchreibweise „entartet“, da keine intermediate nodes (Kids) verwendet werden. Was bei der geringen Anzahl an eingebetteten Dateien (hier 1) auch nicht verwundert. Gedacht ist der Mechanismus zum effizienten Navigieren in großen Mengen gleichartiger Objekte. Diese sind dann (analog zum Pages Tree) als Baum organisiert.
Leider hatten mein Musterrechnungen in ZF1 immer nur Flat Array als Implementierung, da unsere jPod-Bibliothek bei wenigen Einbettungen dies als effizienten Default nimmt. Wenn man darauf besteht, kann man die Einbettung auch immer hierarchisch anlegen (siehe zweites Beispiel), was z.B. pdflib mit deren Implementierung macht. Beide Varianten sind vollkommen PDF und PDF/A konform.
   





Ich hatte die Unterscheidung zw. Flat Array und Name Trees nicht mehr explizit in die Spec aufgenommen, da dies streng genommen rein PDF-spezifische Implementierungsvarianten sind, die nichts mit ZUGFeRD zu tun haben. Wenn die zuständige Bibliothek die Einbettungen PDF/A-konform durchführt, spielt es keine Rolle, ob die eine oder die andere Variante verwendet wird. Leider habe ich nur ein Beispiel in der Spec, und das zeigt eben die Names Tree Variante.
```
