### ISSUE TITLE
[BUG] Exception happens on CLI call

### ISSUE THREAD

**Issue by wurst-hans** [ZUGFeRD/mustangproject#608]
I've integrated Mustang Project into my PHP application and I'm calling the Mustang CLI via exec() call. The command lines for this call look like (source and output files have UUID as name in reality):

`$(which java) -Xmx1G -Dfile.encoding=UTF-8 -jar ./sources/mustang/Mustang-CLI-2.15.0.jar --disable-file-logging --action extract --source ./my/file.pdf 2>/dev/null`

Basically, this works fine. Rarely, it happens, that the JAR throws an exception really fast, with the following content:

```
<?xml version="1.0" encoding="UTF-8"?>
<validation filename="37421442-903c-4794-94bd-17bf6b3beac7" datetime="2024-12-09 16:09:29">
    <pdf />
    <messages>
        <exception type="7">start:1733756969107 must not be &gt;
            finish:1733756968893&lt;stacktrace&gt;[Ljava.lang.StackTraceElement;@5d332969&lt;/stacktrace&gt;</exception>
    </messages>
    <summary status="invalid" />
</validation>
```

This error is absolutely not reproducable and has happened some times now using different source files. For me it seems, that it is not related to the source file itself. When this error occurs and I re-run the command immediately, the validator runs without any problems on second call.

What are these timestamps which lead to the error? And why is a start timestamp *after* the finish timestamp?

**Comment by langfr** [comment]
The xml shown is the content of ./my/result.xml, right ?
Always without any useful information in "stacktrace" ?
The error message seem not to be generated by mustangproject itself, could not find it in the code searching with "git grep 'start:'". Possibly generated by a third party library used.

Instead of throwing away the output to stderr (2>/dev/null) could you redirect stdout and stderr to a file (2>&1 > /tmp/result.txt) ?
Is there any output ?

**Comment by wurst-hans** [comment]
You are right, this is the XML from the result file. It looks always the same, only this short message about a stacktrace. And it's always an error about start and finish time.
I'll try to implement STDOUT/STDERR logging, but as I've said, this error happens rarely, so I'm not aware, when it will happen again.

**Comment by wurst-hans** [comment]
After many tests today, it happened again. Here's the output of STDERR

```
Dec 11, 2024 2:06:22 PM org.verapdf.pd.font.Encoding getName
WARNING: Invalid glyph code: -95
Dec 11, 2024 2:06:22 PM org.verapdf.pd.font.Encoding getName
WARNING: Invalid glyph code: -90
Dec 11, 2024 2:06:22 PM org.verapdf.pd.font.Encoding getName
WARNING: Invalid glyph code: -95
Dec 11, 2024 2:06:22 PM org.verapdf.pd.font.Encoding getName
WARNING: Invalid glyph code: -95
Dec 11, 2024 2:06:22 PM org.verapdf.pd.font.Encoding getName
WARNING: Invalid glyph code: -90
Dec 11, 2024 2:06:22 PM org.verapdf.pd.font.Encoding getName
WARNING: Invalid glyph code: -66
Dec 11, 2024 2:06:22 PM org.verapdf.pd.font.Encoding getName
WARNING: Invalid glyph code: -66
Dec 11, 2024 2:06:22 PM org.verapdf.pd.font.Encoding getName
WARNING: Invalid glyph code: -95
Dec 11, 2024 2:06:22 PM org.verapdf.pd.font.Encoding getName
WARNING: Invalid glyph code: -38
Dec 11, 2024 2:06:22 PM org.verapdf.pd.font.Encoding getName
WARNING: Invalid glyph code: -38
Dec 11, 2024 2:06:22 PM org.verapdf.pd.font.Encoding getName
WARNING: Invalid glyph code: -38
Dec 11, 2024 2:06:22 PM org.verapdf.pd.font.Encoding getName
WARNING: Invalid glyph code: -38
Dec 11, 2024 2:06:22 PM org.verapdf.pd.font.Encoding getName
WARNING: Invalid glyph code: -38
Dec 11, 2024 2:06:22 PM org.verapdf.pd.font.Encoding getName
WARNING: Invalid glyph code: -90
Dec 11, 2024 2:06:22 PM org.verapdf.pd.font.Encoding getName
WARNING: Invalid glyph code: -66
Dec 11, 2024 2:06:22 PM org.verapdf.pd.font.Encoding getName
WARNING: Invalid glyph code: -72
Dec 11, 2024 2:06:22 PM org.verapdf.pd.font.Encoding getName
WARNING: Invalid glyph code: -90
Dec 11, 2024 2:06:21 PM org.verapdf.processor.ProcessorImpl process
WARNING: 9c5d372c-c09c-4793-9c6a-6c7c1359ac7c doesn't appear to be a valid PDF.
14:06:21.672 [main] ERROR o.m.validator.ZUGFeRDValidator - Fatal Error 7: start:1733922381767 must not be > finish:1733922381662
14:06:21.673 [main] INFO  o.m.validator.ZUGFeRDValidator - start:1733922381767 must not be > finish:1733922381662
14:06:21.697 [main] INFO  o.m.validator.ZUGFeRDValidator - Parsed PDF:invalid XML:invalid Signature:null Checksum:null Profile:null Version:null Took:-53ms Errors:[7] UUID: 9c5d372c-c09c-4793-9c6a-6c7c1359ac7c
```

Running the same file again, immediately after exception, it validates successfully (sorry, I can't provide that file currently). It seems to be related to veraPDF. The strange thing are the timestamps in the log. The exception of veraPDF (i.e. the last message from veraPDF itself) has a timestamp one second before the warnings. Additionally all following timestamps of Mustangproject are one second before the veraPDF warnings, too.

**Comment by wurst-hans** [comment]
I'm running this on Linux under WSL. Because it seems not reproducable for you, I think it's related to my environment really. Currently, I've implemented a workaround which checks for string StrackTrace and re-executes the command. So, let's close that ticket for now.
