### ISSUE TITLE
Version 1.5.2 missing in mvn repo

### ISSUE THREAD

**Issue by schube** [ZUGFeRD/mustangproject#61]
I set up a new java project as described here:
http://www.mustangproject.org/use.html

    <repositories>
    <repository>
        <id>mustang-mvn-repo</id>
        <url>https://raw.github.com/ZUGFeRD/mustangproject/mvn-repo/</url>
    </repository>
    </repositories>
    <dependencies>
    <dependency>
        <groupId>org.mustangproject.ZUGFeRD</groupId>
        <artifactId>mustang</artifactId>
        <version>1.5.2</version>
    </dependency>
    <dependency>
        <groupId>commons-logging</groupId>
        <artifactId>commons-logging</artifactId>
        <version>1.1.1</version>
    </dependency>
    <dependency>
        <groupId>com.sun.xml.bind</groupId>
        <artifactId>jaxb-impl</artifactId>
        <version>2.2.5</version>
    </dependency>
    </dependencies>

It does not work, the jar is not found.
`[WARNING] The POM for org.mustangproject.ZUGFeRD:mustang:jar:1.5.2 is missing, no dependency information available`
 When I downgrade to 1.5.1 it works:

     <dependency>
        <groupId>org.mustangproject.ZUGFeRD</groupId>
        <artifactId>mustang</artifactId>
        <version>1.5.1</version>
    </dependency>

**Comment by jstaerk** [comment]
Despite the error in #60 is still present in this release please try again in order to confirm that it works. This was closely related to #52, I regenerated my access token :-/.

**Comment by schube** [comment]
@jstaerk I used 1.5.3 now, which was correctly downloaded from https://raw.github.com/ZUGFeRD/mustangproject/mvn-repo/ so I do not care much about 1.5.2 any more :-)
Thank you for fixing it!
