### ISSUE TITLE
CLI tool, unable to extract from MustangGnuaccountingBeispielRE-20170509_505blanko.pdf

### ISSUE THREAD

**Issue by schube** [ZUGFeRD/mustangproject#62]
Hi!

Mustang 1.5.3 and your very own PDF file (from your website) "MustangGnuaccountingBeispielRE-20170509_505blanko.pdf"

    java -jar mustang-1.5.3.jar -e 
    Source PDF (default: invoice.pdf):MustangGnuaccountingBeispielRE-20170509_505blanko.pdf
    ZUGFeRD XML (default: ZUGFeRD-invoice.xml):out2.xml
    Jul 23, 2018 9:00:33 AM org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB suggestKCMS
    INFORMATION: To get higher rendering speed on java 8 oder 9,
    Jul 23, 2018 9:00:33 AM org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB suggestKCMS
    INFORMATION:   use the option -Dsun.java2d.cmm=sun.java2d.cmm.kcms.KcmsServiceProvider
    Jul 23, 2018 9:00:33 AM org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB suggestKCMS
    INFORMATION:   or call System.setProperty("sun.java2d.cmm",    "sun.java2d.cmm.kcms.KcmsServiceProvider")
    Exception in thread "main" java.lang.NullPointerException
    	at java.util.Objects.requireNonNull(Objects.java:203)
   	at java.nio.file.Files.write(Files.java:3290)
   	at org.mustangproject.toecount.Toecount.main(Toecount.java:371)

It **works** with the PDF file zugferd_invoice.pdf which I linked in #60

**Comment by jstaerk** [comment]
:-) The blanko is the file intentionally without ZF Data developers can download to reproduce code samples e.g. on http://www.mustangproject.org/use.html and add or create XML, the official sample file is http://www.mustangproject.org/files/MustangGnuaccountingBeispielRE-20170509_505.pdf but I agree, the nullpointerexception is not nice, I might fix that.

**Comment by jstaerk** [comment]
It's now fixed in today's 1.5.4
