### ISSUE TITLE
Commandline: provide a way to set input parameters

### ISSUE THREAD

**Issue by Indigo744** [ZUGFeRD/mustangproject#66]
Hello,

For my projects, I don't need to actually build an app from the library.
The [command line ](http://www.mustangproject.org/use.html#commandline) looks good, but sadly it can't be reliably automated.

I would love to be able to specify the parameters directly when calling the tar file.
For instance, when combining a PDF and an XML to generate a FacturX file:
```
java -jar mustang-1.5.4.jar -c myInvoice.pdf myInvoice.xml myInvoice-facturx.pdf 2 basic
```

Do you think it would be possible?

**Comment by jstaerk** [comment]
There is a discussion in the mailing list, I think it was [this post](https://groups.google.com/forum/#!topic/zugferd/Xn2H5CpcksA), Andreas Mause is successfully using "expect" for this purpose. We're also working on a online tool (the idea is a website where you can e.g. upload PDF and XML and merge them): your help would be very much appreciated.

**Comment by Indigo744** [comment]
Ah yes, I do know expect. But I would rather avoid having to resort to such hacky wrappers...

I've never worked in Java, but I could _try_ to look into it if there is no other choice 😸.

**Comment by jstaerk** [comment]
thanks a lot
