### ISSUE TITLE
CLI tool should return nonzero exit code on fatal errors

### ISSUE THREAD

**Issue by hschletz** [ZUGFeRD/mustangproject#69]
The CLI tool returns with an exit code of 0 when there are fatal errors, like
- PDF input file is not PDF-A
- invalid arguments (ex. "--zugferd-profile gfgdf")

This makes it difficult to catch fatal errors from a calling application. We have to catch output from STDERR, which may also contain warnings which we may choose to ignore. Parsing STDERR is an unreliable way to check for errors.

The CLI tool should return witn a nonzero exit code if there are fatal errors.

**Comment by jstaerk** [comment]
Actually you are right. Will become even more important when ZUV is merged. Done in master head, will be part of the next release.
