### ISSUE TITLE
Mustang library without included dependencies

### ISSUE THREAD

**Issue by dovogt** [ZUGFeRD/mustangproject#82]
Is it possible to offer the Mustang library without the included dependencies in the repository. The dependencies should be defined in the included pom.xml.
I am using the library in my environment and there are problems with jaxb. The integration of the library is done with Gradle. In case of version conflicts it resolves gradle. Currently this doesn't work, because all dependencies have been packed into Mustang.jar.

**Comment by jstaerk** [comment]
Feel free to let me know how this could be done, I don't have any idea, I can only say that I manually deploy the unshadowed copy e.g. to http://www.mustangproject.org/deploy/original-mustang-1.6.0.jar

**Comment by dovogt** [comment]
Hello, 
could you please offer version 1.7.6 for download at http://www.mustangproject.org/deploy/original-mustang-1.7.6.jar
