### ISSUE TITLE
Validator does not recognize some pdf/a3-1b

### ISSUE THREAD

**Issue by michafn** [ZUGFeRD/mustangproject#85]
Ref. post on stackoverflow: https://stackoverflow.com/questions/55869953/ghostscript-pdf-a-conversion-problem-on-ubuntu-18-10-and-docker/55873473#55873473

Ref link to files: 
pdf1: https://www.dropbox.com/s/gxjxakd5necaswo/incorrect.pdf?dl=0
pdf2: https://www.dropbox.com/s/56al2jbpe7ikbl4/correct.pdf?dl=0

Description:
I produced two different pdf/a files (from a pdf1.3 as base). Both files have been created using ghostscript `gs -dPDFA -dBATCH -dNOPAUSE -dNOOUTERSAVE -sColorConversionStrategy=sRGB -sDEVICE=pdfwrite -sOutputFile=output.pdf PDFA_def.ps input.pdf
`
However, i ran this conversion in a docker container and on the host system (both running on the same OS and ame tool versions). The pdf/a (incorrect.pdf) has been the conversion done in the docker file. Whereas the correct.pdf is properly processed with mustang, the incorrect.pdf throws an error, that it is not pdf/a compliant. 

Any online validator considers both files to be pdf/a compliant. This leads me to the assumption that there might be a problem in the validation function in mustang. Can anyone confirm the problem?

**Comment by jstaerk** [comment]
I assume you are referring to the check of the input file. That's based on PDFBox' preflightparser (https://pdfbox.apache.org/1.8/cookbook/pdfavalidation.html) and I will have a look but in the meantime can you maybe just bypass it by invoking ZUGFeRDExporter's ignoreA1Errors()?

**Comment by michafn** [comment]
i currently use the jar file, not building it myself. I guess i'll have to got the tough way, change and compile it then. Let me know if you come to a conclusion, i'll test if it works when deactivating the validation.

**Comment by jstaerk** [comment]
e.g. verapdf (https://verapdf.org/) 1.10.6 reports an error in your incorrect.pdf, i will therefore close this issue because I assume the error in the input document: 

Specification: ISO 19005-1:2005, Clause: 6.7.3, Test number: 1 |  
-- | --
If a document information dictionary does appear at a document, then all of its entries that have analogous properties in predefined XMP schemas, shall also be embedded in the file in XMP form with equivalent values. | Failed

**Comment by rui-sereno-artlogic** [comment]
@michafn did you find the solution for this issue? Thank you.
