### ISSUE TITLE
Literal "Ursprungsbeleg: "

### ISSUE THREAD

**Issue by swsch** [ZUGFeRD/mustangproject#93]
The private method `ZUGFeRDTransactionModelConverter.getDocument` prefixes the results of `getReferenceNumber()` with the string literal `"Ursprungsbeleg: "` (line 170).

While this can be convenient if you actually only have a reference _number_, our database uses a general text field containing phrases like "Bestellung xy von egal wann" or sometimes even "persönlich durch xy an dem Datum", which look a bit weird with that prefix.

Can we remove this literal or at least make it configurable so that I can set it to an empty string in my code? I think I can prepare a pull request, just let me know the preferred way.

**Comment by jstaerk** [comment]
I think that is ZF1 only and yes, feel free to send me a PR to remove it
