### ISSUE TITLE
ram:CategoryCode 380 appears in ram:ApplicableTradeTax

### ISSUE THREAD

**Issue by swsch** [ZUGFeRD/mustangproject#95]
The [validation portal](https://www.din-zugferd-validation.org/validationportal/) complains about an invalid CategoryCode in the XML (v1) generated by mustang. There is a *380* in the trade tax total for the invoice, while the CategoryCode is *S* for individual trade tax items. 

```<rsm:CrossIndustryDocument ...>
    <rsm:SpecifiedExchangedDocumentContext>...</rsm:SpecifiedExchangedDocumentContext>
    <rsm:HeaderExchangedDocument>...</rsm:HeaderExchangedDocument>
    <rsm:SpecifiedSupplyChainTradeTransaction>
        <ram:ApplicableSupplyChainTradeAgreement>...</ram:ApplicableSupplyChainTradeAgreement>
        <ram:ApplicableSupplyChainTradeDelivery>...</ram:ApplicableSupplyChainTradeDelivery>
        <ram:ApplicableSupplyChainTradeSettlement>...
            <ram:ApplicableTradeTax>
                <ram:CalculatedAmount currencyID="EUR">68.99</ram:CalculatedAmount>
                <ram:TypeCode>VAT</ram:TypeCode>
                <ram:BasisAmount currencyID="EUR">363.10</ram:BasisAmount>
 ***            <ram:CategoryCode>380</ram:CategoryCode>
                <ram:ApplicablePercent>19.00</ram:ApplicablePercent>
            </ram:ApplicableTradeTax>...
        </ram:ApplicableSupplyChainTradeSettlement>
        <ram:IncludedSupplyChainTradeLineItem>
            <ram:AssociatedDocumentLineDocument>...</ram:AssociatedDocumentLineDocument>
            <ram:SpecifiedSupplyChainTradeAgreement>...</ram:SpecifiedSupplyChainTradeAgreement>
            <ram:SpecifiedSupplyChainTradeDelivery>...</ram:SpecifiedSupplyChainTradeDelivery>
            <ram:SpecifiedSupplyChainTradeSettlement>
                <ram:ApplicableTradeTax>
                    <ram:TypeCode>VAT</ram:TypeCode>
 ***                <ram:CategoryCode>S</ram:CategoryCode>
                    <ram:ApplicablePercent>19.00</ram:ApplicablePercent>
                </ram:ApplicableTradeTax>...
            </ram:SpecifiedSupplyChainTradeSettlement>
```

Looking at the code, this could originate in ZUGFeRDTransactionModelConverter.getVATPercentAmountMap (line 927), where a VATAmount is created as
```
VATAmount itemVATAmount = new VATAmount(..., trans.getDocumentCode());
```
and as far as my late-evening understanding goes, the last argument provides the *380* that shows up in the total. 

The same code is used a few lines below around line 961 for the LogisticsServiceCharges. My current sample document does not use those, but I expect the validation portal to complain about that, too.

**Comment by jstaerk** [comment]
would "S" be the correct code?

**Comment by swsch** [comment]
For my invoices it would be, since they only use one VAT rate, which is classified as `S` for the individual items. And if it were "just me", I'd put "S" there with a "FIXME" comment next to it and move on...

What gets me wondering, though, is that the wrong code in the constructor has not been changed at all during processing. If I understand that code correctly, it should basically calculate the sums grouped by tax rate, and if a non-existent tax rate survives this, there is probably a larger problem than an invalid category code.

**Comment by swsch** [comment]
I found an example in the documentation of the 1.0 ZUGFeRD format (Das ZUGFeRD-Format_1p0.pdf, page 50/131), where different tax rates have all been classified with CategoryCode `S`, so it turns out that "just make that `S`" seems to be a good fix.

```Beispiel zum Ausweis der Steuerbeträge je Steuersatz auf Dokumentenebene:
<ram:ApplicableTradeTax>
  <ram:CalculatedAmount currencyID="EUR">61.07</ram:CalculatedAmount>
  <ram:TypeCode>VAT</ram:TypeCode>
  <ram:BasisAmount currencyID="EUR">321.40</ram:BasisAmount>
  <ram:CategoryCode>S</ram:CategoryCode>
  <ram:ApplicablePercent>19.00</ram:ApplicablePercent>
</ram:ApplicableTradeTax>
<ram:ApplicableTradeTax>
  <ram:CalculatedAmount currencyID="EUR">8.93</ram:CalculatedAmount>
  <ram:TypeCode>VAT</ram:TypeCode>
  <ram:BasisAmount currencyID="EUR">127.59</ram:BasisAmount>
  <ram:CategoryCode>S</ram:CategoryCode>
  <ram:ApplicablePercent>7.00</ram:ApplicablePercent>
</ram:ApplicableTradeTax>
```

Would it make sense to update the class VATAmount? Its use of `documentCode` instead of  `categoryCode` (along with smart IDEs and muscle memory) seems to be the cause of this problem.

Rename the field and the parameter name of the constructor, add suitable accessors and deprecate the current ones? I'll draft a pull request later today.
